/*$$$LICENCE_NORDIC_STANDARD<2022>$$$*/

#ifndef NRFX_INTERCONNECT_APB_HALTIUM_RADIOCORE_H__
#define NRFX_INTERCONNECT_APB_HALTIUM_RADIOCORE_H__

#include <soc/interconnect/apb/nrfx_interconnect_apb_local.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef NRFX_DPPI020_CONFIG_OWNED_CHANNELS_MASK
#define NRFX_DPPI020_CONFIG_OWNED_CHANNELS_MASK NRFX_BIT_MASK(DPPIC020_CH_NUM)
#endif

#ifndef NRFX_DPPI030_CONFIG_OWNED_CHANNELS_MASK
#define NRFX_DPPI030_CONFIG_OWNED_CHANNELS_MASK NRFX_BIT_MASK(DPPIC030_CH_NUM)
#endif

#if (NRFX_DPPI_LOCAL_CONFIG_OWNED_CHANNELS_MASK_BY_INST_NUM(020) > \
     NRFX_BIT_MASK(DPPIC020_CH_NUM))
#error "Invalid mask for DPPIC020 owned channels defined."
#endif

#if ((NRFX_DPPI_PUB_CONFIG_ALLOWED_CHANNELS_MASK_BY_INST_NUM(020) | \
     NRFX_DPPI_SUB_CONFIG_ALLOWED_CHANNELS_MASK_BY_INST_NUM(020)) > \
     NRFX_DPPI_LOCAL_CONFIG_OWNED_CHANNELS_MASK_BY_INST_NUM(020))
#error "Invalid mask for DPPIC020 subscibe/publish defined."
#endif

#if (NRFX_DPPI_LOCAL_CONFIG_OWNED_CHANNELS_MASK_BY_INST_NUM(030) > \
     NRFX_BIT_MASK(DPPIC030_CH_NUM))
#error "Invalid mask for DPPIC030 owned channels defined."
#endif

#if ((NRFX_DPPI_PUB_CONFIG_ALLOWED_CHANNELS_MASK_BY_INST_NUM(030) | \
     NRFX_DPPI_SUB_CONFIG_ALLOWED_CHANNELS_MASK_BY_INST_NUM(030)) > \
     NRFX_DPPI_LOCAL_CONFIG_OWNED_CHANNELS_MASK_BY_INST_NUM(030))
#error "Invalid mask for DPPIC030 subscibe/publish defined."
#endif

#ifndef NRFX_INTERCONNECT_APB_LOCAL_DPPI_DEFINE
#define NRFX_INTERCONNECT_APB_LOCAL_DPPI_DEFINE \
NRFX_DPPI_LOCAL_CHANNELS_ENTRY(020);            \
NRFX_DPPI_LOCAL_CHANNELS_ENTRY(030);
#endif // NRFX_INTERCONNECT_APB_LOCAL_DPPI_DEFINE

#define NRFX_INTERCONNECT_APB_LOCAL_BUSES_PROP                             \
{                                                                          \
    NRFX_INTERCONNECT_APB_LOCAL_PROP_ENTRY(020, NRF_PPIB020, 0x10000) /* APB2 */ \
    NRFX_INTERCONNECT_APB_LOCAL_PROP_ENTRY(030, NRF_PPIB030, 0x10000) /* APB3 */ \
}

#ifdef __cplusplus
}
#endif

#endif // NRFX_INTERCONNECT_APB_HALTIUM_RADIOCORE_H__
