/*$$$LICENCE_NORDIC_STANDARD<2022>$$$*/

#ifndef NRFX_INTERCONNECT_APB_HALTIUM_CELLCORE_H__
#define NRFX_INTERCONNECT_APB_HALTIUM_CELLCORE_H__

#ifdef __cplusplus
extern "C" {
#endif

#ifndef NRFX_DPPI0_CONFIG_OWNED_CHANNELS_MASK
#define NRFX_DPPI0_CONFIG_OWNED_CHANNELS_MASK NRFX_BIT_MASK(DPPIC0_CH_NUM)
#endif

#ifndef NRFX_DPPI1_CONFIG_OWNED_CHANNELS_MASK
#define NRFX_DPPI1_CONFIG_OWNED_CHANNELS_MASK NRFX_BIT_MASK(DPPIC1_CH_NUM)
#endif

#if (NRFX_DPPI_LOCAL_CONFIG_OWNED_CHANNELS_MASK_BY_INST_NUM(0) > \
     NRFX_BIT_MASK(DPPIC0_CH_NUM))
#error "Invalid mask for DPPIC0 owned channels defined."
#endif

#if ((NRFX_DPPI_PUB_CONFIG_ALLOWED_CHANNELS_MASK_BY_INST_NUM(0) | \
     NRFX_DPPI_SUB_CONFIG_ALLOWED_CHANNELS_MASK_BY_INST_NUM(0)) > \
     NRFX_DPPI_LOCAL_CONFIG_OWNED_CHANNELS_MASK_BY_INST_NUM(0))
#error "Invalid mask for DPPIC0 subscibe/publish defined."
#endif

#if (NRFX_DPPI_LOCAL_CONFIG_OWNED_CHANNELS_MASK_BY_INST_NUM(1) > \
     NRFX_BIT_MASK(DPPIC1_CH_NUM))
#error "Invalid mask for DPPIC1 owned channels defined."
#endif

#if ((NRFX_DPPI_PUB_CONFIG_ALLOWED_CHANNELS_MASK_BY_INST_NUM(1) | \
     NRFX_DPPI_SUB_CONFIG_ALLOWED_CHANNELS_MASK_BY_INST_NUM(1)) > \
     NRFX_DPPI_LOCAL_CONFIG_OWNED_CHANNELS_MASK_BY_INST_NUM(1))
#error "Invalid mask for DPPIC1 subscibe/publish defined."
#endif

#ifndef NRFX_INTERCONNECT_APB_LOCAL_DPPI_DEFINE
#define NRFX_INTERCONNECT_APB_LOCAL_DPPI_DEFINE \
NRFX_DPPI_LOCAL_CHANNELS_ENTRY(0);              \
NRFX_DPPI_LOCAL_CHANNELS_ENTRY(1);
#endif // NRFX_INTERCONNECT_APB_LOCAL_DPPI_DEFINE

#define NRFX_INTERCONNECT_APB_LOCAL_BUSES_PROP                               \
{                                                                            \
    NRFX_INTERCONNECT_APB_LOCAL_PROP_ENTRY(0, NRF_PPIB1, 0x10000) /* APB2 */ \
    NRFX_INTERCONNECT_APB_LOCAL_PROP_ENTRY(1, NRF_PPIB2, 0x10000) /* APB3 */ \
}

#ifdef __cplusplus
}
#endif

#endif // NRFX_INTERCONNECT_APB_HALTIUM_CELLCORE_H__
