/*$$$LICENCE_NORDIC_STANDARD<2022>$$$*/

#ifndef NRFX_INTERCONNECT_APB_HALTIUM_SYSCTRL_H__
#define NRFX_INTERCONNECT_APB_HALTIUM_SYSCTRL_H__

#ifdef __cplusplus
extern "C" {
#endif

#define NRFX_DPPI_LOCAL_DEFINE

#define NRFX_APB_LOCAL_INTERCONNECT {}

#ifdef __cplusplus
}
#endif

#endif // NRFX_INTERCONNECT_APB_HALTIUM_SYSCTRL_H__
