/*

Copyright (c) 2010 - 2022, Nordic Semiconductor ASA

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form, except as embedded into a Nordic
   Semiconductor ASA integrated circuit in a product or a software update for
   such product, must reproduce the above copyright notice, this list of
   conditions and the following disclaimer in the documentation and/or other
   materials provided with the distribution.

3. Neither the name of Nordic Semiconductor ASA nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

4. This software, with or without modification, must only be used with a
   Nordic Semiconductor ASA integrated circuit.

5. Any software provided in binary form under this license must not be reverse
   engineered, decompiled, modified and/or disassembled.

THIS SOFTWARE IS PROVIDED BY NORDIC SEMICONDUCTOR ASA "AS IS" AND ANY EXPRESS
OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY, NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL NORDIC SEMICONDUCTOR ASA OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef HALTIUM_BBPR_PERIPHERALS_H
#define HALTIUM_BBPR_PERIPHERALS_H

#ifdef __cplusplus
    extern "C" {
#endif

/*VPR CSR registers*/
#define VPRCSR_PRESENT
#define VPRCSR_COUNT 1

#define VPRCSR_HARTNUM 0
#define VPRCSR_MCLICBASERESET 4096
#define VPRCSR_MULDIV 2
#define VPRCSR_HIBERNATE 1
#define VPRCSR_DBG 1
#define VPRCSR_REMAP 0
#define VPRCSR_BUSWIDTH 64
#define VPRCSR_BKPT 2
#define VPRCSR_RT_VIO_PINS 0
#define VPRCSR_RT_SPLIT_SEC 0
#define VPRCSR_RT_SHIFT_PRESENT 0
#define VPRCSR_RT_SHIFT_START 0
#define VPRCSR_RT_SHIFT_LENGHT 32
#define VPRCSR_VEVIF_NTASKS 32
#define VPRCSR_VEVIF_NDPPI 32
#define VPRCSR_VEVIF_NEVENTS 32
#define VPRCSR_RST_UNRECOV 0
#define VPRCSR_BEXT 0

/*VPR peripheral registers*/
#define VPR_PRESENT
#define VPR_COUNT 1

#define VPR_INIT_PC_RESET_VALUE 0
#define VPR_VPR_START_RESET_VALUE 0
#define VPR_RAM_BASE_ADDR 0
#define VPR_RAM_SZ 0
#define VPR_VPRSAVEDCTX 0
#define VPR_VPRSAVEADDR 0
#define VPR_VPRREMAPADDRVTOB 0
#define VPR_VEVIF_NTASKS 32
#define VPR_VEVIF_NDPPI 32
#define VPR_VEVIF_NEVENTS 32

/*Factory Information Configuration Registers*/
#define FICR_PRESENT
#define FICR_COUNT 1

/*USBHSCORE*/
#define USBHSCORE_PRESENT
#define USBHSCORE_COUNT 1

/*I3CCORE*/
#define I3CCORE_PRESENT
#define I3CCORE_COUNT 2

/*System Trace Macrocell data buffer*/
#define STMDATA_PRESENT
#define STMDATA_COUNT 1

/*TDDCONF*/
#define TDDCONF_PRESENT
#define TDDCONF_COUNT 1

/*Trace buffer monitor*/
#define TBM_PRESENT
#define TBM_COUNT 1

/*GENERIC*/
#define GENERIC_PRESENT
#define GENERIC_COUNT 3

/*System Trace Macrocell*/
#define STM_PRESENT
#define STM_COUNT 1

/*Trace Port Interface Unit*/
#define TPIU_PRESENT
#define TPIU_COUNT 1

/*Cross-Trigger Interface control*/
#define CTI_PRESENT
#define CTI_COUNT 2

/*ATB Replicator module*/
#define ATBREPLICATOR_PRESENT
#define ATBREPLICATOR_COUNT 4

/*ATB funnel module*/
#define ATBFUNNEL_PRESENT
#define ATBFUNNEL_COUNT 4

/*GPIO Tasks and Events*/
#define GPIOTE_PRESENT
#define GPIOTE_COUNT 2

/*Global Real-time counter*/
#define GRTC_PRESENT
#define GRTC_COUNT 1

/*USBHS*/
#define USBHS_PRESENT
#define USBHS_COUNT 1

/*External Memory Interface*/
#define EXMIF_PRESENT
#define EXMIF_COUNT 1

/*AUXPLL*/
#define AUXPLL_PRESENT
#define AUXPLL_COUNT 1

/*AUXPM*/
#define AUXPM_PRESENT
#define AUXPM_COUNT 1

/*IPCT APB registers*/
#define IPCT_PRESENT
#define IPCT_COUNT 2

/*MUTEX*/
#define MUTEX_PRESENT
#define MUTEX_COUNT 2

/*I3C*/
#define I3C_PRESENT
#define I3C_COUNT 2

/*Controller Area Network*/
#define CAN_PRESENT
#define CAN_COUNT 1

/*Distributed programmable peripheral interconnect controller*/
#define DPPIC_PRESENT
#define DPPIC_COUNT 8

#define DPPIC120_HASCHANNELGROUPS 1

#define DPPIC130_HASCHANNELGROUPS 1

#define DPPIC131_HASCHANNELGROUPS 1

#define DPPIC132_HASCHANNELGROUPS 1

#define DPPIC133_HASCHANNELGROUPS 1

#define DPPIC134_HASCHANNELGROUPS 1

#define DPPIC135_HASCHANNELGROUPS 1

#define DPPIC136_HASCHANNELGROUPS 1

/*Timer/Counter*/
#define TIMER_PRESENT
#define TIMER_COUNT 10

/*Pulse width modulation unit*/
#define PWM_PRESENT
#define PWM_COUNT 5

/*SPI Slave*/
#define SPIS_PRESENT
#define SPIS_COUNT 9

#define SPIS120_LEGACYPSEL 0
#define SPIS120_LEGACYEDMA 0
#define SPIS120_EASYDMALISTINCLUDED 0
#define SPIS120_EASYDMAMODEINCLUDED 0
#define SPIS120_EASYDMAFULLLPMODEINCLUDED 0

#define SPIS130_LEGACYPSEL 0
#define SPIS130_LEGACYEDMA 0
#define SPIS130_EASYDMALISTINCLUDED 0
#define SPIS130_EASYDMAMODEINCLUDED 0
#define SPIS130_EASYDMAFULLLPMODEINCLUDED 0

#define SPIS131_LEGACYPSEL 0
#define SPIS131_LEGACYEDMA 0
#define SPIS131_EASYDMALISTINCLUDED 0
#define SPIS131_EASYDMAMODEINCLUDED 0
#define SPIS131_EASYDMAFULLLPMODEINCLUDED 0

#define SPIS132_LEGACYPSEL 0
#define SPIS132_LEGACYEDMA 0
#define SPIS132_EASYDMALISTINCLUDED 0
#define SPIS132_EASYDMAMODEINCLUDED 0
#define SPIS132_EASYDMAFULLLPMODEINCLUDED 0

#define SPIS133_LEGACYPSEL 0
#define SPIS133_LEGACYEDMA 0
#define SPIS133_EASYDMALISTINCLUDED 0
#define SPIS133_EASYDMAMODEINCLUDED 0
#define SPIS133_EASYDMAFULLLPMODEINCLUDED 0

#define SPIS134_LEGACYPSEL 0
#define SPIS134_LEGACYEDMA 0
#define SPIS134_EASYDMALISTINCLUDED 0
#define SPIS134_EASYDMAMODEINCLUDED 0
#define SPIS134_EASYDMAFULLLPMODEINCLUDED 0

#define SPIS135_LEGACYPSEL 0
#define SPIS135_LEGACYEDMA 0
#define SPIS135_EASYDMALISTINCLUDED 0
#define SPIS135_EASYDMAMODEINCLUDED 0
#define SPIS135_EASYDMAFULLLPMODEINCLUDED 0

#define SPIS136_LEGACYPSEL 0
#define SPIS136_LEGACYEDMA 0
#define SPIS136_EASYDMALISTINCLUDED 0
#define SPIS136_EASYDMAMODEINCLUDED 0
#define SPIS136_EASYDMAFULLLPMODEINCLUDED 0

#define SPIS137_LEGACYPSEL 0
#define SPIS137_LEGACYEDMA 0
#define SPIS137_EASYDMALISTINCLUDED 0
#define SPIS137_EASYDMAMODEINCLUDED 0
#define SPIS137_EASYDMAFULLLPMODEINCLUDED 0

/*UART with EasyDMA*/
#define UARTE_PRESENT
#define UARTE_COUNT 9

#define UARTE120_EASYDMA5 0
#define UARTE120_EASYDMALISTINCLUDED 0
#define UARTE120_EASYDMAMODEINCLUDED 0
#define UARTE120_EASYDMAFULLLPMODEINCLUDED 0

#define UARTE130_EASYDMA5 0
#define UARTE130_EASYDMALISTINCLUDED 0
#define UARTE130_EASYDMAMODEINCLUDED 0
#define UARTE130_EASYDMAFULLLPMODEINCLUDED 0

#define UARTE131_EASYDMA5 0
#define UARTE131_EASYDMALISTINCLUDED 0
#define UARTE131_EASYDMAMODEINCLUDED 0
#define UARTE131_EASYDMAFULLLPMODEINCLUDED 0

#define UARTE132_EASYDMA5 0
#define UARTE132_EASYDMALISTINCLUDED 0
#define UARTE132_EASYDMAMODEINCLUDED 0
#define UARTE132_EASYDMAFULLLPMODEINCLUDED 0

#define UARTE133_EASYDMA5 0
#define UARTE133_EASYDMALISTINCLUDED 0
#define UARTE133_EASYDMAMODEINCLUDED 0
#define UARTE133_EASYDMAFULLLPMODEINCLUDED 0

#define UARTE134_EASYDMA5 0
#define UARTE134_EASYDMALISTINCLUDED 0
#define UARTE134_EASYDMAMODEINCLUDED 0
#define UARTE134_EASYDMAFULLLPMODEINCLUDED 0

#define UARTE135_EASYDMA5 0
#define UARTE135_EASYDMALISTINCLUDED 0
#define UARTE135_EASYDMAMODEINCLUDED 0
#define UARTE135_EASYDMAFULLLPMODEINCLUDED 0

#define UARTE136_EASYDMA5 0
#define UARTE136_EASYDMALISTINCLUDED 0
#define UARTE136_EASYDMAMODEINCLUDED 0
#define UARTE136_EASYDMAFULLLPMODEINCLUDED 0

#define UARTE137_EASYDMA5 0
#define UARTE137_EASYDMALISTINCLUDED 0
#define UARTE137_EASYDMAMODEINCLUDED 0
#define UARTE137_EASYDMAFULLLPMODEINCLUDED 0

/*Serial Peripheral Interface Master with EasyDMA*/
#define SPIM_PRESENT
#define SPIM_COUNT 10

#define SPIM120_EASYDMALISTINCLUDED 0
#define SPIM120_EASYDMAMODEINCLUDED 0
#define SPIM120_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM120_HSSPI 1

#define SPIM121_EASYDMALISTINCLUDED 0
#define SPIM121_EASYDMAMODEINCLUDED 0
#define SPIM121_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM121_HSSPI 1

#define SPIM130_EASYDMALISTINCLUDED 0
#define SPIM130_EASYDMAMODEINCLUDED 0
#define SPIM130_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM130_HSSPI 1

#define SPIM131_EASYDMALISTINCLUDED 0
#define SPIM131_EASYDMAMODEINCLUDED 0
#define SPIM131_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM131_HSSPI 1

#define SPIM132_EASYDMALISTINCLUDED 0
#define SPIM132_EASYDMAMODEINCLUDED 0
#define SPIM132_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM132_HSSPI 1

#define SPIM133_EASYDMALISTINCLUDED 0
#define SPIM133_EASYDMAMODEINCLUDED 0
#define SPIM133_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM133_HSSPI 1

#define SPIM134_EASYDMALISTINCLUDED 0
#define SPIM134_EASYDMAMODEINCLUDED 0
#define SPIM134_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM134_HSSPI 1

#define SPIM135_EASYDMALISTINCLUDED 0
#define SPIM135_EASYDMAMODEINCLUDED 0
#define SPIM135_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM135_HSSPI 1

#define SPIM136_EASYDMALISTINCLUDED 0
#define SPIM136_EASYDMAMODEINCLUDED 0
#define SPIM136_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM136_HSSPI 1

#define SPIM137_EASYDMALISTINCLUDED 0
#define SPIM137_EASYDMAMODEINCLUDED 0
#define SPIM137_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM137_HSSPI 1

/*I2C compatible Two-Wire Master Interface with EasyDMA*/
#define TWIM_PRESENT
#define TWIM_COUNT 9

#define TWIM120_EASYDMALISTINCLUDED 0
#define TWIM120_EASYDMAMODEINCLUDED 0
#define TWIM120_EASYDMAFULLLPMODEINCLUDED 0

#define TWIM130_EASYDMALISTINCLUDED 0
#define TWIM130_EASYDMAMODEINCLUDED 0
#define TWIM130_EASYDMAFULLLPMODEINCLUDED 0

#define TWIM131_EASYDMALISTINCLUDED 0
#define TWIM131_EASYDMAMODEINCLUDED 0
#define TWIM131_EASYDMAFULLLPMODEINCLUDED 0

#define TWIM132_EASYDMALISTINCLUDED 0
#define TWIM132_EASYDMAMODEINCLUDED 0
#define TWIM132_EASYDMAFULLLPMODEINCLUDED 0

#define TWIM133_EASYDMALISTINCLUDED 0
#define TWIM133_EASYDMAMODEINCLUDED 0
#define TWIM133_EASYDMAFULLLPMODEINCLUDED 0

#define TWIM134_EASYDMALISTINCLUDED 0
#define TWIM134_EASYDMAMODEINCLUDED 0
#define TWIM134_EASYDMAFULLLPMODEINCLUDED 0

#define TWIM135_EASYDMALISTINCLUDED 0
#define TWIM135_EASYDMAMODEINCLUDED 0
#define TWIM135_EASYDMAFULLLPMODEINCLUDED 0

#define TWIM136_EASYDMALISTINCLUDED 0
#define TWIM136_EASYDMAMODEINCLUDED 0
#define TWIM136_EASYDMAFULLLPMODEINCLUDED 0

#define TWIM137_EASYDMALISTINCLUDED 0
#define TWIM137_EASYDMAMODEINCLUDED 0
#define TWIM137_EASYDMAFULLLPMODEINCLUDED 0

/*Real-time counter*/
#define RTC_PRESENT
#define RTC_COUNT 2

/*Watchdog Timer*/
#define WDT_PRESENT
#define WDT_COUNT 2

/*Event generator unit*/
#define EGU_PRESENT
#define EGU_COUNT 1

#define EGU130_PEND 0

/*GPIO Port*/
#define GPIO_PRESENT
#define GPIO_COUNT 16

#define P0_DRIVECTRL 0
#define P0_PWRCTRL 0

#define P1_DRIVECTRL 0
#define P1_PWRCTRL 0

#define P2_DRIVECTRL 0
#define P2_PWRCTRL 0

#define P3_DRIVECTRL 0
#define P3_PWRCTRL 0

#define P4_DRIVECTRL 0
#define P4_PWRCTRL 0

#define P5_DRIVECTRL 0
#define P5_PWRCTRL 0

#define P6_DRIVECTRL 1
#define P6_PWRCTRL 0

#define P7_DRIVECTRL 1
#define P7_PWRCTRL 0

#define P8_DRIVECTRL 1
#define P8_PWRCTRL 0

#define P9_DRIVECTRL 0
#define P9_PWRCTRL 1

#define P10_DRIVECTRL 0
#define P10_PWRCTRL 0

#define P11_DRIVECTRL 0
#define P11_PWRCTRL 0

#define P12_DRIVECTRL 0
#define P12_PWRCTRL 0

#define P13_DRIVECTRL 0
#define P13_PWRCTRL 0

#define P14_DRIVECTRL 0
#define P14_PWRCTRL 0

#define P15_DRIVECTRL 0
#define P15_PWRCTRL 0

/*GPIO Internal*/
#define GPIOINTERNAL_PRESENT
#define GPIOINTERNAL_COUNT 1

/*Analog to Digital Converter*/
#define SAADC_PRESENT
#define SAADC_COUNT 1

#define SAADC_EASYDMA5 0
#define SAADC_EASYDMALISTINCLUDED 0
#define SAADC_EASYDMAMODEINCLUDED 0
#define SAADC_EASYDMAFULLLPMODEINCLUDED 0

/*Comparator*/
#define COMP_PRESENT
#define COMP_COUNT 1

/*Low-power comparator*/
#define LPCOMP_PRESENT
#define LPCOMP_COUNT 1

/*Temperature Sensor*/
#define TEMP_PRESENT
#define TEMP_COUNT 1

/*NFC-A compatible radio NFC-A compatible radio*/
#define NFCT_PRESENT
#define NFCT_COUNT 1

/*Inter-IC Sound*/
#define I2S_PRESENT
#define I2S_COUNT 2

/*Pulse Density Modulation (Digital Microphone) Interface*/
#define PDM_PRESENT
#define PDM_COUNT 1

#define PDM_EASYDMA5 0
#define PDM_EASYDMALISTINCLUDED 0
#define PDM_EASYDMAMODEINCLUDED 0
#define PDM_EASYDMAFULLLPMODEINCLUDED 0

/*Quadrature Decoder*/
#define QDEC_PRESENT
#define QDEC_COUNT 2

#define QDEC130_LEGACYPSEL 0

#define QDEC131_LEGACYPSEL 0

/*SIM card interface*/
#define SIMIF_PRESENT
#define SIMIF_COUNT 1

/*MipiRffe Master*/
#define MIPIRFFE_PRESENT
#define MIPIRFFE_COUNT 1

/*I2C compatible Two-Wire Slave Interface with EasyDMA*/
#define TWIS_PRESENT
#define TWIS_COUNT 8

#define TWIS130_EASYDMALISTINCLUDED 0
#define TWIS130_EASYDMAMODEINCLUDED 0
#define TWIS130_EASYDMAFULLLPMODEINCLUDED 0

#define TWIS131_EASYDMALISTINCLUDED 0
#define TWIS131_EASYDMAMODEINCLUDED 0
#define TWIS131_EASYDMAFULLLPMODEINCLUDED 0

#define TWIS132_EASYDMALISTINCLUDED 0
#define TWIS132_EASYDMAMODEINCLUDED 0
#define TWIS132_EASYDMAFULLLPMODEINCLUDED 0

#define TWIS133_EASYDMALISTINCLUDED 0
#define TWIS133_EASYDMAMODEINCLUDED 0
#define TWIS133_EASYDMAFULLLPMODEINCLUDED 0

#define TWIS134_EASYDMALISTINCLUDED 0
#define TWIS134_EASYDMAMODEINCLUDED 0
#define TWIS134_EASYDMAFULLLPMODEINCLUDED 0

#define TWIS135_EASYDMALISTINCLUDED 0
#define TWIS135_EASYDMAMODEINCLUDED 0
#define TWIS135_EASYDMAFULLLPMODEINCLUDED 0

#define TWIS136_EASYDMALISTINCLUDED 0
#define TWIS136_EASYDMAMODEINCLUDED 0
#define TWIS136_EASYDMAFULLLPMODEINCLUDED 0

#define TWIS137_EASYDMALISTINCLUDED 0
#define TWIS137_EASYDMAMODEINCLUDED 0
#define TWIS137_EASYDMAFULLLPMODEINCLUDED 0


#ifdef __cplusplus
}
#endif
#endif /* HALTIUM_BBPR_PERIPHERALS_H */
