/*

Copyright (c) 2010 - 2023, Nordic Semiconductor ASA

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form, except as embedded into a Nordic
   Semiconductor ASA integrated circuit in a product or a software update for
   such product, must reproduce the above copyright notice, this list of
   conditions and the following disclaimer in the documentation and/or other
   materials provided with the distribution.

3. Neither the name of Nordic Semiconductor ASA nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

4. This software, with or without modification, must only be used with a
   Nordic Semiconductor ASA integrated circuit.

5. Any software provided in binary form under this license must not be reverse
   engineered, decompiled, modified and/or disassembled.

THIS SOFTWARE IS PROVIDED BY NORDIC SEMICONDUCTOR ASA "AS IS" AND ANY EXPRESS
OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY, NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL NORDIC SEMICONDUCTOR ASA OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#ifndef MOONLIGHT_APPLICATION_PERIPHERALS_H
#define MOONLIGHT_APPLICATION_PERIPHERALS_H

#ifdef __cplusplus
    extern "C" {
#endif

/*CACHEDATA*/
#define CACHEDATA_PRESENT
#define CACHEDATA_COUNT 1

#define ICACHEDATA_NUMSETS 256
#define ICACHEDATA_NUMWAYS 2
#define ICACHEDATA_NUMDATAUNIT 4
#define ICACHEDATA_DATAWIDTH 2

/*CACHEINFO*/
#define CACHEINFO_PRESENT
#define CACHEINFO_COUNT 1

#define ICACHEINFO_NUMSETS 256
#define ICACHEINFO_NUMWAYS 2
#define ICACHEINFO_NUMDATAUNIT 8
#define ICACHEINFO_DATAWIDTH 4
#define ICACHEINFO_TAGWIDTH 24
#define ICACHEINFO_DU_EXTENSION 0

/*CM33 SubSystem*/
#define CM33SS_PRESENT
#define CM33SS_COUNT 1

/*Cache*/
#define CACHE_PRESENT
#define CACHE_COUNT 1

#define ICACHE_VIRTUALCACHE 0
#define ICACHE_FLUSH 0
#define ICACHE_CLEAN 0
#define ICACHE_NONCACHEABLEMISS 0
#define ICACHE_BUSWIDTH 64

/*Software interrupt*/
#define SWI_PRESENT
#define SWI_COUNT 4

/*Factory Information Configuration Registers*/
#define SICR_PRESENT
#define SICR_COUNT 1

/*User Information Configuration Registers*/
#define UICR_PRESENT
#define UICR_COUNT 1

/*Factory Information Configuration Registers*/
#define FICR_PRESENT
#define FICR_COUNT 1

/*CRACENCORE*/
#define CRACENCORE_PRESENT
#define CRACENCORE_COUNT 1

#define CRACENCORE_CRYPTMSTRDMAREGS 1
#define CRACENCORE_CRYPTMSTRHWREGS 1
#define CRACENCORE_RNGCONTROLREGS 1
#define CRACENCORE_PKREGS 1
#define CRACENCORE_IKGREGS 1
#define CRACENCORE_RNGDATAREGS 1
#define CRACENCORE_PKDATAMEMORYREGS 1
#define CRACENCORE_PKUCODEREGS 1
#define CRACENCORE_CRACENRESETVALUES 1
#define CRACENCORE_SHA3RESETVALUES 0

/*System protection unit*/
#define SPU_PRESENT
#define SPU_COUNT 4

#define SPU00_GRTCSECONDARYOFFSET 1
#define SPU00_BELLS 0
#define SPU00_IPCT 0
#define SPU00_DPPI 1
#define SPU00_GPIOTE 0
#define SPU00_GRTC 0
#define SPU00_GPIO 1
#define SPU00_CRACEN 1
#define SPU00_MRAMC 0
#define SPU00_COEXC 0
#define SPU00_ANTSWC 0
#define SPU00_TDD 0

#define SPU10_GRTCSECONDARYOFFSET 1
#define SPU10_BELLS 0
#define SPU10_IPCT 0
#define SPU10_DPPI 1
#define SPU10_GPIOTE 0
#define SPU10_GRTC 0
#define SPU10_GPIO 0
#define SPU10_CRACEN 0
#define SPU10_MRAMC 0
#define SPU10_COEXC 0
#define SPU10_ANTSWC 0
#define SPU10_TDD 0

#define SPU20_GRTCSECONDARYOFFSET 1
#define SPU20_BELLS 0
#define SPU20_IPCT 0
#define SPU20_DPPI 1
#define SPU20_GPIOTE 1
#define SPU20_GRTC 1
#define SPU20_GPIO 1
#define SPU20_CRACEN 0
#define SPU20_MRAMC 0
#define SPU20_COEXC 0
#define SPU20_ANTSWC 0
#define SPU20_TDD 0

#define SPU30_GRTCSECONDARYOFFSET 1
#define SPU30_BELLS 0
#define SPU30_IPCT 0
#define SPU30_DPPI 1
#define SPU30_GPIOTE 1
#define SPU30_GRTC 0
#define SPU30_GPIO 1
#define SPU30_CRACEN 0
#define SPU30_MRAMC 0
#define SPU30_COEXC 0
#define SPU30_ANTSWC 0
#define SPU30_TDD 0

/*Memory Privilege Controller*/
#define MPC_PRESENT
#define MPC_COUNT 1

#define MPC00_EXTEND_CLOCK_REQ 0
#define MPC00_OVERRIDE_GRAN 4000

/*Distributed programmable peripheral interconnect controller*/
#define DPPIC_PRESENT
#define DPPIC_COUNT 4

#define DPPIC00_HASCHANNELGROUPS 1
#define DPPIC00_CH_NUM 8
#define DPPIC00_GROUP_NUM 2

#define DPPIC10_HASCHANNELGROUPS 1
#define DPPIC10_CH_NUM 24
#define DPPIC10_GROUP_NUM 6

#define DPPIC20_HASCHANNELGROUPS 1
#define DPPIC20_CH_NUM 16
#define DPPIC20_GROUP_NUM 6

#define DPPIC30_HASCHANNELGROUPS 1
#define DPPIC30_CH_NUM 4
#define DPPIC30_GROUP_NUM 2

/*PPIB APB registers*/
#define PPIB_PRESENT
#define PPIB_COUNT 8

#define PPIB00_NTASKSEVENTS 8

#define PPIB01_NTASKSEVENTS 8

#define PPIB10_NTASKSEVENTS 8

#define PPIB11_NTASKSEVENTS 16

#define PPIB20_NTASKSEVENTS 8

#define PPIB21_NTASKSEVENTS 16

#define PPIB22_NTASKSEVENTS 4

#define PPIB30_NTASKSEVENTS 4

/*Key management unit*/
#define KMU_PRESENT
#define KMU_COUNT 1

#define KMU_KEYSLOTBITS 8
#define KMU_KEYSLOTNUM 256

/*Accelerated Address Resolver*/
#define AAR_PRESENT
#define AAR_COUNT 2

/*AES CCM Mode Encryption*/
#define CCM_PRESENT
#define CCM_COUNT 2

#define CCM00_AMOUNTREG 0
#define CCM00_ONTHEFLYDECRYPTION 0

#define CCM10_AMOUNTREG 0
#define CCM10_ONTHEFLYDECRYPTION 1

/*AES ECB Mode Encryption*/
#define ECB_PRESENT
#define ECB_COUNT 2

#define ECB00_AMOUNTREG 0

#define ECB10_AMOUNTREG 0

/*CRACEN*/
#define CRACEN_PRESENT
#define CRACEN_COUNT 1

#define CRACEN_CRYPTOACCELERATOR 1

/*Serial Peripheral Interface*/
#define SPI_PRESENT
#define SPI_COUNT 5

#define SPI00_LEGACYPSEL 0
#define SPI00_PRESCALER_PRESENT 1
#define SPI00_PRESCALER_DIVISOR_RANGE 1
#define SPI00_CORE_FREQUENCY 192

#define SPI20_LEGACYPSEL 0
#define SPI20_PRESCALER_PRESENT 1
#define SPI20_PRESCALER_DIVISOR_RANGE 1
#define SPI20_CORE_FREQUENCY 16

#define SPI21_LEGACYPSEL 0
#define SPI21_PRESCALER_PRESENT 1
#define SPI21_PRESCALER_DIVISOR_RANGE 1
#define SPI21_CORE_FREQUENCY 16

#define SPI22_LEGACYPSEL 0
#define SPI22_PRESCALER_PRESENT 1
#define SPI22_PRESCALER_DIVISOR_RANGE 1
#define SPI22_CORE_FREQUENCY 16

#define SPI30_LEGACYPSEL 0
#define SPI30_PRESCALER_PRESENT 1
#define SPI30_PRESCALER_DIVISOR_RANGE 1
#define SPI30_CORE_FREQUENCY 16

/*Serial Peripheral Interface Master with EasyDMA*/
#define SPIM_PRESENT
#define SPIM_COUNT 5

#define SPIM00_EASYDMA5 1
#define SPIM00_EASYDMATEMP 0
#define SPIM00_EASYDMALISTINCLUDED 1
#define SPIM00_EASYDMAMODEINCLUDED 0
#define SPIM00_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM00_EASYDMAPATTERNMATCHERINCLUDED 1
#define SPIM00_EASYDMANUMMATCHCHANNELS 4
#define SPIM00_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define SPIM00_EASYDMASTOPTASKINCLUDED 1
#define SPIM00_MAX_DATARATE 32
#define SPIM00_EASYDMA_MAXCNT_SIZE 16
#define SPIM00_FEATURE_HARDWARE_CSN_PRESENT 1
#define SPIM00_FEATURE_HARDWARE_DCX_PRESENT 1
#define SPIM00_FEATURE_RXDELAY_PRESENT 1
#define SPIM00_STALL_STATUS_PRESENT 0
#define SPIM00_STALL_STATUS_TX_PRESENT 1
#define SPIM00_HSSPI 0
#define SPIM00_HIGH_SPEED_DOMAIN 0
#define SPIM00_MULTIPLE_CHIPSELECT 1
#define SPIM00_NUM_CHIPSELECT 1
#define SPIM00_CORE_FREQUENCY 192
#define SPIM00_PRESCALER_PRESENT 1
#define SPIM00_PRESCALER_DIVISOR_RANGE 123

#define SPIM20_EASYDMA5 1
#define SPIM20_EASYDMATEMP 0
#define SPIM20_EASYDMALISTINCLUDED 1
#define SPIM20_EASYDMAMODEINCLUDED 0
#define SPIM20_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM20_EASYDMAPATTERNMATCHERINCLUDED 1
#define SPIM20_EASYDMANUMMATCHCHANNELS 4
#define SPIM20_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define SPIM20_EASYDMASTOPTASKINCLUDED 1
#define SPIM20_MAX_DATARATE 8
#define SPIM20_EASYDMA_MAXCNT_SIZE 16
#define SPIM20_FEATURE_HARDWARE_CSN_PRESENT 1
#define SPIM20_FEATURE_HARDWARE_DCX_PRESENT 1
#define SPIM20_FEATURE_RXDELAY_PRESENT 0
#define SPIM20_STALL_STATUS_PRESENT 0
#define SPIM20_STALL_STATUS_TX_PRESENT 0
#define SPIM20_HSSPI 0
#define SPIM20_HIGH_SPEED_DOMAIN 0
#define SPIM20_MULTIPLE_CHIPSELECT 1
#define SPIM20_NUM_CHIPSELECT 1
#define SPIM20_CORE_FREQUENCY 16
#define SPIM20_PRESCALER_PRESENT 1
#define SPIM20_PRESCALER_DIVISOR_RANGE 125

#define SPIM21_EASYDMA5 1
#define SPIM21_EASYDMATEMP 0
#define SPIM21_EASYDMALISTINCLUDED 1
#define SPIM21_EASYDMAMODEINCLUDED 0
#define SPIM21_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM21_EASYDMAPATTERNMATCHERINCLUDED 1
#define SPIM21_EASYDMANUMMATCHCHANNELS 4
#define SPIM21_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define SPIM21_EASYDMASTOPTASKINCLUDED 1
#define SPIM21_MAX_DATARATE 8
#define SPIM21_EASYDMA_MAXCNT_SIZE 16
#define SPIM21_FEATURE_HARDWARE_CSN_PRESENT 1
#define SPIM21_FEATURE_HARDWARE_DCX_PRESENT 1
#define SPIM21_FEATURE_RXDELAY_PRESENT 0
#define SPIM21_STALL_STATUS_PRESENT 0
#define SPIM21_STALL_STATUS_TX_PRESENT 0
#define SPIM21_HSSPI 0
#define SPIM21_HIGH_SPEED_DOMAIN 0
#define SPIM21_MULTIPLE_CHIPSELECT 1
#define SPIM21_NUM_CHIPSELECT 1
#define SPIM21_CORE_FREQUENCY 16
#define SPIM21_PRESCALER_PRESENT 1
#define SPIM21_PRESCALER_DIVISOR_RANGE 125

#define SPIM22_EASYDMA5 1
#define SPIM22_EASYDMATEMP 0
#define SPIM22_EASYDMALISTINCLUDED 1
#define SPIM22_EASYDMAMODEINCLUDED 0
#define SPIM22_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM22_EASYDMAPATTERNMATCHERINCLUDED 1
#define SPIM22_EASYDMANUMMATCHCHANNELS 4
#define SPIM22_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define SPIM22_EASYDMASTOPTASKINCLUDED 1
#define SPIM22_MAX_DATARATE 8
#define SPIM22_EASYDMA_MAXCNT_SIZE 16
#define SPIM22_FEATURE_HARDWARE_CSN_PRESENT 1
#define SPIM22_FEATURE_HARDWARE_DCX_PRESENT 0
#define SPIM22_FEATURE_RXDELAY_PRESENT 0
#define SPIM22_STALL_STATUS_PRESENT 0
#define SPIM22_STALL_STATUS_TX_PRESENT 0
#define SPIM22_HSSPI 0
#define SPIM22_HIGH_SPEED_DOMAIN 0
#define SPIM22_MULTIPLE_CHIPSELECT 1
#define SPIM22_NUM_CHIPSELECT 1
#define SPIM22_CORE_FREQUENCY 16
#define SPIM22_PRESCALER_PRESENT 1
#define SPIM22_PRESCALER_DIVISOR_RANGE 125

#define SPIM30_EASYDMA5 1
#define SPIM30_EASYDMATEMP 0
#define SPIM30_EASYDMALISTINCLUDED 1
#define SPIM30_EASYDMAMODEINCLUDED 0
#define SPIM30_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM30_EASYDMAPATTERNMATCHERINCLUDED 1
#define SPIM30_EASYDMANUMMATCHCHANNELS 4
#define SPIM30_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define SPIM30_EASYDMASTOPTASKINCLUDED 1
#define SPIM30_MAX_DATARATE 8
#define SPIM30_EASYDMA_MAXCNT_SIZE 16
#define SPIM30_FEATURE_HARDWARE_CSN_PRESENT 1
#define SPIM30_FEATURE_HARDWARE_DCX_PRESENT 0
#define SPIM30_FEATURE_RXDELAY_PRESENT 0
#define SPIM30_STALL_STATUS_PRESENT 0
#define SPIM30_STALL_STATUS_TX_PRESENT 0
#define SPIM30_HSSPI 0
#define SPIM30_HIGH_SPEED_DOMAIN 0
#define SPIM30_MULTIPLE_CHIPSELECT 1
#define SPIM30_NUM_CHIPSELECT 1
#define SPIM30_CORE_FREQUENCY 16
#define SPIM30_PRESCALER_PRESENT 1
#define SPIM30_PRESCALER_DIVISOR_RANGE 125

/*SPI Slave*/
#define SPIS_PRESENT
#define SPIS_COUNT 5

#define SPIS00_LEGACYPSEL 0
#define SPIS00_LEGACYEDMA 0
#define SPIS00_EASYDMA_MAXCNT_SIZE 16
#define SPIS00_EASYDMA5 1
#define SPIS00_EASYDMATEMP 0
#define SPIS00_EASYDMALISTINCLUDED 0
#define SPIS00_EASYDMAMODEINCLUDED 0
#define SPIS00_EASYDMAFULLLPMODEINCLUDED 0
#define SPIS00_EASYDMAPATTERNMATCHERINCLUDED 1
#define SPIS00_EASYDMANUMMATCHCHANNELS 4
#define SPIS00_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define SPIS00_EASYDMASTOPTASKINCLUDED 1

#define SPIS20_LEGACYPSEL 0
#define SPIS20_LEGACYEDMA 0
#define SPIS20_EASYDMA_MAXCNT_SIZE 16
#define SPIS20_EASYDMA5 1
#define SPIS20_EASYDMATEMP 0
#define SPIS20_EASYDMALISTINCLUDED 0
#define SPIS20_EASYDMAMODEINCLUDED 0
#define SPIS20_EASYDMAFULLLPMODEINCLUDED 0
#define SPIS20_EASYDMAPATTERNMATCHERINCLUDED 1
#define SPIS20_EASYDMANUMMATCHCHANNELS 4
#define SPIS20_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define SPIS20_EASYDMASTOPTASKINCLUDED 1

#define SPIS21_LEGACYPSEL 0
#define SPIS21_LEGACYEDMA 0
#define SPIS21_EASYDMA_MAXCNT_SIZE 16
#define SPIS21_EASYDMA5 1
#define SPIS21_EASYDMATEMP 0
#define SPIS21_EASYDMALISTINCLUDED 0
#define SPIS21_EASYDMAMODEINCLUDED 0
#define SPIS21_EASYDMAFULLLPMODEINCLUDED 0
#define SPIS21_EASYDMAPATTERNMATCHERINCLUDED 1
#define SPIS21_EASYDMANUMMATCHCHANNELS 4
#define SPIS21_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define SPIS21_EASYDMASTOPTASKINCLUDED 1

#define SPIS22_LEGACYPSEL 0
#define SPIS22_LEGACYEDMA 0
#define SPIS22_EASYDMA_MAXCNT_SIZE 16
#define SPIS22_EASYDMA5 1
#define SPIS22_EASYDMATEMP 0
#define SPIS22_EASYDMALISTINCLUDED 0
#define SPIS22_EASYDMAMODEINCLUDED 0
#define SPIS22_EASYDMAFULLLPMODEINCLUDED 0
#define SPIS22_EASYDMAPATTERNMATCHERINCLUDED 1
#define SPIS22_EASYDMANUMMATCHCHANNELS 4
#define SPIS22_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define SPIS22_EASYDMASTOPTASKINCLUDED 1

#define SPIS30_LEGACYPSEL 0
#define SPIS30_LEGACYEDMA 0
#define SPIS30_EASYDMA_MAXCNT_SIZE 16
#define SPIS30_EASYDMA5 1
#define SPIS30_EASYDMATEMP 0
#define SPIS30_EASYDMALISTINCLUDED 0
#define SPIS30_EASYDMAMODEINCLUDED 0
#define SPIS30_EASYDMAFULLLPMODEINCLUDED 0
#define SPIS30_EASYDMAPATTERNMATCHERINCLUDED 1
#define SPIS30_EASYDMANUMMATCHCHANNELS 4
#define SPIS30_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define SPIS30_EASYDMASTOPTASKINCLUDED 1

/*UART with EasyDMA*/
#define UARTE_PRESENT
#define UARTE_COUNT 5

#define UARTE00_EASYDMA_MAXCNT_SIZE 8
#define UARTE00_EASYDMA5 1
#define UARTE00_EASYDMATEMP 0
#define UARTE00_TIMEOUT_INTERRUPT 0
#define UARTE00_CONFIGURABLE_DATA_FRAME_SIZE 0
#define UARTE00_CORE_CLOCK_16 1
#define UARTE00_CORE_CLOCK_320 0
#define UARTE00_EASYDMALISTINCLUDED 0
#define UARTE00_EASYDMAMODEINCLUDED 0
#define UARTE00_EASYDMAFULLLPMODEINCLUDED 0
#define UARTE00_EASYDMAPATTERNMATCHERINCLUDED 1
#define UARTE00_EASYDMANUMMATCHCHANNELS 4
#define UARTE00_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define UARTE00_EASYDMASTOPTASKINCLUDED 1

#define UARTE20_EASYDMA_MAXCNT_SIZE 8
#define UARTE20_EASYDMA5 1
#define UARTE20_EASYDMATEMP 0
#define UARTE20_TIMEOUT_INTERRUPT 0
#define UARTE20_CONFIGURABLE_DATA_FRAME_SIZE 0
#define UARTE20_CORE_CLOCK_16 1
#define UARTE20_CORE_CLOCK_320 0
#define UARTE20_EASYDMALISTINCLUDED 0
#define UARTE20_EASYDMAMODEINCLUDED 0
#define UARTE20_EASYDMAFULLLPMODEINCLUDED 0
#define UARTE20_EASYDMAPATTERNMATCHERINCLUDED 1
#define UARTE20_EASYDMANUMMATCHCHANNELS 4
#define UARTE20_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define UARTE20_EASYDMASTOPTASKINCLUDED 1

#define UARTE21_EASYDMA_MAXCNT_SIZE 8
#define UARTE21_EASYDMA5 1
#define UARTE21_EASYDMATEMP 0
#define UARTE21_TIMEOUT_INTERRUPT 0
#define UARTE21_CONFIGURABLE_DATA_FRAME_SIZE 0
#define UARTE21_CORE_CLOCK_16 1
#define UARTE21_CORE_CLOCK_320 0
#define UARTE21_EASYDMALISTINCLUDED 0
#define UARTE21_EASYDMAMODEINCLUDED 0
#define UARTE21_EASYDMAFULLLPMODEINCLUDED 0
#define UARTE21_EASYDMAPATTERNMATCHERINCLUDED 1
#define UARTE21_EASYDMANUMMATCHCHANNELS 4
#define UARTE21_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define UARTE21_EASYDMASTOPTASKINCLUDED 1

#define UARTE22_EASYDMA_MAXCNT_SIZE 8
#define UARTE22_EASYDMA5 1
#define UARTE22_EASYDMATEMP 0
#define UARTE22_TIMEOUT_INTERRUPT 0
#define UARTE22_CONFIGURABLE_DATA_FRAME_SIZE 0
#define UARTE22_CORE_CLOCK_16 1
#define UARTE22_CORE_CLOCK_320 0
#define UARTE22_EASYDMALISTINCLUDED 0
#define UARTE22_EASYDMAMODEINCLUDED 0
#define UARTE22_EASYDMAFULLLPMODEINCLUDED 0
#define UARTE22_EASYDMAPATTERNMATCHERINCLUDED 1
#define UARTE22_EASYDMANUMMATCHCHANNELS 4
#define UARTE22_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define UARTE22_EASYDMASTOPTASKINCLUDED 1

#define UARTE30_EASYDMA_MAXCNT_SIZE 8
#define UARTE30_EASYDMA5 1
#define UARTE30_EASYDMATEMP 0
#define UARTE30_TIMEOUT_INTERRUPT 0
#define UARTE30_CONFIGURABLE_DATA_FRAME_SIZE 0
#define UARTE30_CORE_CLOCK_16 1
#define UARTE30_CORE_CLOCK_320 0
#define UARTE30_EASYDMALISTINCLUDED 0
#define UARTE30_EASYDMAMODEINCLUDED 0
#define UARTE30_EASYDMAFULLLPMODEINCLUDED 0
#define UARTE30_EASYDMAPATTERNMATCHERINCLUDED 1
#define UARTE30_EASYDMANUMMATCHCHANNELS 4
#define UARTE30_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define UARTE30_EASYDMASTOPTASKINCLUDED 1

/*RRAM controller*/
#define RRAMC_PRESENT
#define RRAMC_COUNT 1

#define RRAMC_NRRAMWORDSIZE 128
#define RRAMC_NCONSUMERS 4
#define RRAMC_NREGIONS 5
#define RRAMC_ECCCORRADDR 0
#define RRAMC_NWRITEBUFSIZE 32
#define RRAMC_WRITEBUFSIZE8EN 0
#define RRAMC_WRITEBUFSIZE16EN 0
#define RRAMC_WRITEBUFSIZE32EN 1
#define RRAMC_REGION0ADDR 0x00FFF000
#define RRAMC_REGION0SIZE 4
#define RRAMC_REGION0READ 1
#define RRAMC_REGION0WRITE 1
#define RRAMC_REGION0EXECUTE 0
#define RRAMC_REGION0SECURE 0
#define RRAMC_REGION0OWNER 0
#define RRAMC_REGION0WRITEONCE 1
#define RRAMC_REGION0LOCK 0
#define RRAMC_REGION1ADDR 0x00FFE000
#define RRAMC_REGION1SIZE 4
#define RRAMC_REGION1READ 1
#define RRAMC_REGION1WRITE 1
#define RRAMC_REGION1EXECUTE 0
#define RRAMC_REGION1SECURE 0
#define RRAMC_REGION1OWNER 0
#define RRAMC_REGION1WRITEONCE 1
#define RRAMC_REGION1LOCK 0
#define RRAMC_REGION2ADDR 0x00FFC000
#define RRAMC_REGION2SIZE 8
#define RRAMC_REGION2READ 1
#define RRAMC_REGION2WRITE 1
#define RRAMC_REGION2EXECUTE 0
#define RRAMC_REGION2SECURE 1
#define RRAMC_REGION2OWNER 2
#define RRAMC_REGION2WRITEONCE 0
#define RRAMC_REGION2LOCK 0
#define RRAMC_REGION3ADDR 0x00000000
#define RRAMC_REGION3SIZE 0
#define RRAMC_REGION3READ 1
#define RRAMC_REGION3WRITE 1
#define RRAMC_REGION3EXECUTE 1
#define RRAMC_REGION3SECURE 1
#define RRAMC_REGION3OWNER 0
#define RRAMC_REGION3WRITEONCE 0
#define RRAMC_REGION3LOCK 0
#define RRAMC_REGION4ADDR 0
#define RRAMC_REGION4SIZE 0x000000000
#define RRAMC_REGION4READ 1
#define RRAMC_REGION4WRITE 1
#define RRAMC_REGION4EXECUTE 1
#define RRAMC_REGION4SECURE 1
#define RRAMC_REGION4OWNER 0
#define RRAMC_REGION4WRITEONCE 0
#define RRAMC_REGION4LOCK 0

/*VPR peripheral registers*/
#define VPR_PRESENT
#define VPR_COUNT 1

#define VPR00_INIT_PC_RESET_VALUE 0
#define VPR00_VPR_START_RESET_VALUE 0
#define VPR00_RAM_BASE_ADDR 0
#define VPR00_RAM_SZ 0
#define VPR00_VPRSAVEDCTX_REGNAME
#define VPR00_VPRSAVEDCTX_REGBIT
#define VPR00_RETAINED 0
#define VPR00_VPRSAVEDCTX 1
#define VPR00_VPRSAVEADDR 0
#define VPR00_VPRREMAPADDRVTOB 0
#define VPR00_VEVIF_NTASKS 32
#define VPR00_VEVIF_TASKS_MASK 4294967295
#define VPR00_VEVIF_NDPPI 32
#define VPR00_VEVIF_NEVENTS 32
#define VPR00_DEBUGGER_OFFSET 1024

/*GPIO Port*/
#define GPIO_PRESENT
#define GPIO_COUNT 3

#define P2_PIN_NUM 11
#define P2_PINS_PRESENT 2047
#define P2_DRIVECTRL 0
#define P2_PWRCTRL 0
#define P2_PWRCTRL_SEPARATE_REG 0
#define P2_PIN_OWNER_SEC 0

#define P1_PIN_NUM 16
#define P1_PINS_PRESENT 65535
#define P1_DRIVECTRL 0
#define P1_PWRCTRL 0
#define P1_PWRCTRL_SEPARATE_REG 0
#define P1_PIN_OWNER_SEC 0

#define P0_PIN_NUM 5
#define P0_PINS_PRESENT 31
#define P0_DRIVECTRL 0
#define P0_PWRCTRL 0
#define P0_PWRCTRL_SEPARATE_REG 0
#define P0_PIN_OWNER_SEC 0

/*Control access port*/
#define CTRLAPPERI_PRESENT
#define CTRLAPPERI_COUNT 1

/*Trace and debug control*/
#define TAD_PRESENT
#define TAD_COUNT 1

#define TAD_TADFORCEON 0
#define TAD_TAD_HAS_TASKS 0

/*Timer/Counter*/
#define TIMER_PRESENT
#define TIMER_COUNT 7

#define TIMER00_CC_NUM 6
#define TIMER00_MAX_SIZE 32

#define TIMER10_CC_NUM 8
#define TIMER10_MAX_SIZE 32

#define TIMER20_CC_NUM 6
#define TIMER20_MAX_SIZE 32

#define TIMER21_CC_NUM 6
#define TIMER21_MAX_SIZE 32

#define TIMER22_CC_NUM 6
#define TIMER22_MAX_SIZE 32

#define TIMER23_CC_NUM 6
#define TIMER23_MAX_SIZE 32

#define TIMER24_CC_NUM 6
#define TIMER24_MAX_SIZE 32

/*PCGCSlave*/
#define PCGCSLAVE_PRESENT
#define PCGCSLAVE_COUNT 2

#define PCGCS00_PENALTYTASKS 0

#define PCGCS30_PENALTYTASKS 0

/*Real-time counter*/
#define RTC_PRESENT
#define RTC_COUNT 2

#define RTC10_CC_NUM 4

#define RTC30_CC_NUM 4

/*Event generator unit*/
#define EGU_PRESENT
#define EGU_COUNT 2

#define EGU10_PEND 0
#define EGU10_CH_NUM 16

#define EGU20_PEND 0
#define EGU20_CH_NUM 6

/*2.4 GHz radio*/
#define RADIO_PRESENT
#define RADIO_COUNT 1

#define RADIO_ADPLLCOMPANION_INCLUDE_DMA 0
#define RADIO_PERPOWER 1

/*I2C compatible Two-Wire Master Interface with EasyDMA*/
#define TWIM_PRESENT
#define TWIM_COUNT 4

#define TWIM20_EASYDMA5 1
#define TWIM20_EASYDMATEMP 0
#define TWIM20_EASYDMALISTINCLUDED 0
#define TWIM20_EASYDMAMODEINCLUDED 0
#define TWIM20_EASYDMAFULLLPMODEINCLUDED 0
#define TWIM20_EASYDMAPATTERNMATCHERINCLUDED 1
#define TWIM20_EASYDMANUMMATCHCHANNELS 4
#define TWIM20_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define TWIM20_EASYDMASTOPTASKINCLUDED 1

#define TWIM21_EASYDMA5 1
#define TWIM21_EASYDMATEMP 0
#define TWIM21_EASYDMALISTINCLUDED 0
#define TWIM21_EASYDMAMODEINCLUDED 0
#define TWIM21_EASYDMAFULLLPMODEINCLUDED 0
#define TWIM21_EASYDMAPATTERNMATCHERINCLUDED 1
#define TWIM21_EASYDMANUMMATCHCHANNELS 4
#define TWIM21_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define TWIM21_EASYDMASTOPTASKINCLUDED 1

#define TWIM22_EASYDMA5 1
#define TWIM22_EASYDMATEMP 0
#define TWIM22_EASYDMALISTINCLUDED 0
#define TWIM22_EASYDMAMODEINCLUDED 0
#define TWIM22_EASYDMAFULLLPMODEINCLUDED 0
#define TWIM22_EASYDMAPATTERNMATCHERINCLUDED 1
#define TWIM22_EASYDMANUMMATCHCHANNELS 4
#define TWIM22_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define TWIM22_EASYDMASTOPTASKINCLUDED 1

#define TWIM30_EASYDMA5 1
#define TWIM30_EASYDMATEMP 0
#define TWIM30_EASYDMALISTINCLUDED 0
#define TWIM30_EASYDMAMODEINCLUDED 0
#define TWIM30_EASYDMAFULLLPMODEINCLUDED 0
#define TWIM30_EASYDMAPATTERNMATCHERINCLUDED 1
#define TWIM30_EASYDMANUMMATCHCHANNELS 4
#define TWIM30_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define TWIM30_EASYDMASTOPTASKINCLUDED 1

/*I2C compatible Two-Wire Slave Interface with EasyDMA*/
#define TWIS_PRESENT
#define TWIS_COUNT 4

#define TWIS20_EASYDMA5 1
#define TWIS20_EASYDMATEMP 0
#define TWIS20_EASYDMALISTINCLUDED 0
#define TWIS20_EASYDMAMODEINCLUDED 0
#define TWIS20_EASYDMAFULLLPMODEINCLUDED 0
#define TWIS20_EASYDMAPATTERNMATCHERINCLUDED 1
#define TWIS20_EASYDMANUMMATCHCHANNELS 4
#define TWIS20_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define TWIS20_EASYDMASTOPTASKINCLUDED 1

#define TWIS21_EASYDMA5 1
#define TWIS21_EASYDMATEMP 0
#define TWIS21_EASYDMALISTINCLUDED 0
#define TWIS21_EASYDMAMODEINCLUDED 0
#define TWIS21_EASYDMAFULLLPMODEINCLUDED 0
#define TWIS21_EASYDMAPATTERNMATCHERINCLUDED 1
#define TWIS21_EASYDMANUMMATCHCHANNELS 4
#define TWIS21_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define TWIS21_EASYDMASTOPTASKINCLUDED 1

#define TWIS22_EASYDMA5 1
#define TWIS22_EASYDMATEMP 0
#define TWIS22_EASYDMALISTINCLUDED 0
#define TWIS22_EASYDMAMODEINCLUDED 0
#define TWIS22_EASYDMAFULLLPMODEINCLUDED 0
#define TWIS22_EASYDMAPATTERNMATCHERINCLUDED 1
#define TWIS22_EASYDMANUMMATCHCHANNELS 4
#define TWIS22_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define TWIS22_EASYDMASTOPTASKINCLUDED 1

#define TWIS30_EASYDMA5 1
#define TWIS30_EASYDMATEMP 0
#define TWIS30_EASYDMALISTINCLUDED 0
#define TWIS30_EASYDMAMODEINCLUDED 0
#define TWIS30_EASYDMAFULLLPMODEINCLUDED 0
#define TWIS30_EASYDMAPATTERNMATCHERINCLUDED 1
#define TWIS30_EASYDMANUMMATCHCHANNELS 4
#define TWIS30_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define TWIS30_EASYDMASTOPTASKINCLUDED 1

/*Memory configuration*/
#define MEMCONF_PRESENT
#define MEMCONF_COUNT 1

#define MEMCONF_RETTRIM 1
#define MEMCONF_REPAIR 0
#define MEMCONF_POWER 1
#define MEMCONF_RET2 0

/*Pulse width modulation unit*/
#define PWM_PRESENT
#define PWM_COUNT 3

#define PWM20_EASYDMA5 1
#define PWM20_EASYDMATEMP 0
#define PWM20_IDLE_OUT 0
#define PWM20_COMPARE_MATCH 0
#define PWM20_FEATURES_V2 0
#define PWM20_NO_FEATURES_V2 1
#define PWM20_EASYDMALISTINCLUDED 0
#define PWM20_EASYDMAMODEINCLUDED 0
#define PWM20_EASYDMAFULLLPMODEINCLUDED 0
#define PWM20_EASYDMAPATTERNMATCHERINCLUDED 1
#define PWM20_EASYDMANUMMATCHCHANNELS 4
#define PWM20_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define PWM20_EASYDMASTOPTASKINCLUDED 1

#define PWM21_EASYDMA5 1
#define PWM21_EASYDMATEMP 0
#define PWM21_IDLE_OUT 0
#define PWM21_COMPARE_MATCH 0
#define PWM21_FEATURES_V2 0
#define PWM21_NO_FEATURES_V2 1
#define PWM21_EASYDMALISTINCLUDED 0
#define PWM21_EASYDMAMODEINCLUDED 0
#define PWM21_EASYDMAFULLLPMODEINCLUDED 0
#define PWM21_EASYDMAPATTERNMATCHERINCLUDED 1
#define PWM21_EASYDMANUMMATCHCHANNELS 4
#define PWM21_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define PWM21_EASYDMASTOPTASKINCLUDED 1

#define PWM22_EASYDMA5 1
#define PWM22_EASYDMATEMP 0
#define PWM22_IDLE_OUT 0
#define PWM22_COMPARE_MATCH 0
#define PWM22_FEATURES_V2 0
#define PWM22_NO_FEATURES_V2 1
#define PWM22_EASYDMALISTINCLUDED 0
#define PWM22_EASYDMAMODEINCLUDED 0
#define PWM22_EASYDMAFULLLPMODEINCLUDED 0
#define PWM22_EASYDMAPATTERNMATCHERINCLUDED 1
#define PWM22_EASYDMANUMMATCHCHANNELS 4
#define PWM22_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define PWM22_EASYDMASTOPTASKINCLUDED 1

/*Analog to Digital Converter*/
#define SAADC_PRESENT
#define SAADC_COUNT 1

#define SAADC_EASYDMA5 0
#define SAADC_EASYDMATEMP 1
#define SAADC_PSEL_V2 0
#define SAADC_TASKS_CALIBRATEGAIN 0
#define SAADC_EASYDMALISTINCLUDED 0
#define SAADC_EASYDMAMODEINCLUDED 0
#define SAADC_EASYDMAFULLLPMODEINCLUDED 0
#define SAADC_EASYDMAPATTERNMATCHERINCLUDED 0
#define SAADC_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define SAADC_EASYDMASTOPTASKINCLUDED 1

/*NFC-A compatible radio NFC-A compatible radio*/
#define NFCT_PRESENT
#define NFCT_COUNT 1

#define NFCT_EASYDMA5 0
#define NFCT_EASYDMATEMP 1

/*Temperature Sensor*/
#define TEMP_PRESENT
#define TEMP_COUNT 1

/*GPIO Tasks and Events*/
#define GPIOTE_PRESENT
#define GPIOTE_COUNT 2

#define GPIOTE20_GPIOTE_NCHANNELS 8
#define GPIOTE20_GPIOTE_NPORTEVENTS 1
#define GPIOTE20_GPIOTE_NINTERRUPTS 2

#define GPIOTE30_GPIOTE_NCHANNELS 4
#define GPIOTE30_GPIOTE_NPORTEVENTS 1
#define GPIOTE30_GPIOTE_NINTERRUPTS 2

/*Tamper controller*/
#define TAMPC_PRESENT
#define TAMPC_COUNT 1

#define TAMPC_ERASEPROTECT 1

/*Inter-IC Sound*/
#define I2S_PRESENT
#define I2S_COUNT 1

#define I2S20_EASYDMA5 0
#define I2S20_EASYDMATEMP 1
#define I2S20_EASYDMA_MAXCNT_SIZE 14

/*PCGC Master*/
#define PCGCMASTER_PRESENT
#define PCGCMASTER_COUNT 2

#define PCGCM20_POWERCONSUMPTIONCALC 1
#define PCGCM20_SETPWRCONTHRESHOLDBASE 1
#define PCGCM20_CLOCKFORCEREG 1
#define PCGCM20_MASTERFORCEREG 1

#define PCGCM30_POWERCONSUMPTIONCALC 1
#define PCGCM30_SETPWRCONTHRESHOLDBASE 1
#define PCGCM30_CLOCKFORCEREG 1
#define PCGCM30_MASTERFORCEREG 1

/*Quadrature Decoder*/
#define QDEC_PRESENT
#define QDEC_COUNT 2

#define QDEC20_LEGACYPSEL 0

#define QDEC21_LEGACYPSEL 0

/*Global Real-time counter*/
#define GRTC_PRESENT
#define GRTC_COUNT 1

#define GRTC_MSBWIDTH 15
#define GRTC_NCC 12
#define GRTC_NTIMEOUT 16
#define GRTC_NDOMAIN 16
#define GRTC_GRTC_NINTERRUPTS 3
#define GRTC_PWMREGS 1
#define GRTC_CLKOUTREG 1
#define GRTC_CLKSELREG 1

/*Comparator*/
#define COMP_PRESENT
#define COMP_COUNT 1

/*Low-power comparator*/
#define LPCOMP_PRESENT
#define LPCOMP_COUNT 1

/*Watchdog Timer*/
#define WDT_PRESENT
#define WDT_COUNT 2

#define WDT30_START_ON_RESET 0
#define WDT30_CRV_RESETVALUE 4294967295
#define WDT30_ALLOW_STOP 0

#define WDT31_START_ON_RESET 0
#define WDT31_CRV_RESETVALUE 4294967295
#define WDT31_ALLOW_STOP 0

/*Clock management*/
#define CLOCK_PRESENT
#define CLOCK_COUNT 1

/*Power control*/
#define POWER_PRESENT
#define POWER_COUNT 1

/*Reset control*/
#define RESET_PRESENT
#define RESET_COUNT 1

/*Oscillator control*/
#define OSCILLATORS_PRESENT
#define OSCILLATORS_COUNT 1

/*Voltage regulators*/
#define REGULATORS_PRESENT
#define REGULATORS_COUNT 1

/*Main voltage regulator*/
#define VREGMAIN_PRESENT
#define VREGMAIN_COUNT 1


#ifdef __cplusplus
}
#endif
#endif /* MOONLIGHT_APPLICATION_PERIPHERALS_H */

