/*

Copyright (c) 2010 - 2022, Nordic Semiconductor ASA

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form, except as embedded into a Nordic
   Semiconductor ASA integrated circuit in a product or a software update for
   such product, must reproduce the above copyright notice, this list of
   conditions and the following disclaimer in the documentation and/or other
   materials provided with the distribution.

3. Neither the name of Nordic Semiconductor ASA nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

4. This software, with or without modification, must only be used with a
   Nordic Semiconductor ASA integrated circuit.

5. Any software provided in binary form under this license must not be reverse
   engineered, decompiled, modified and/or disassembled.

THIS SOFTWARE IS PROVIDED BY NORDIC SEMICONDUCTOR ASA "AS IS" AND ANY EXPRESS
OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY, NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL NORDIC SEMICONDUCTOR ASA OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#ifndef NRF54H20_ENGA_SYSCTRL_PERIPHERALS_H
#define NRF54H20_ENGA_SYSCTRL_PERIPHERALS_H

#ifdef __cplusplus
    extern "C" {
#endif

#include <stdbool.h>
/*VPR CSR registers*/
#define VPRCSR_PRESENT
#define VPRCSR_COUNT 1

#define VPRCSR_HARTNUM 12
#define VPRCSR_MCLICBASERESET 1603047424
#define VPRCSR_MULDIV 1
#define VPRCSR_HIBERNATE 1
#define VPRCSR_DBG 1
#define VPRCSR_REMAP 1
#define VPRCSR_BUSWIDTH 64
#define VPRCSR_BKPT 1
#define VPRCSR_VIOPINS 4
#define VPRCSR_RT_SPLIT_SEC 1
#define VPRCSR_RT_SHIFT_PRESENT 0
#define VPRCSR_RT_SHIFT_START 0
#define VPRCSR_RT_SHIFT_LENGTH 32
#define VPRCSR_VEVIF_NTASKS_MIN 0
#define VPRCSR_VEVIF_NTASKS_MAX 31
#define VPRCSR_VEVIF_TASKS_MASK 4294963455
#define VPRCSR_VEVIF_NDPPI_MIN 24
#define VPRCSR_VEVIF_NDPPI_MAX 27
#define VPRCSR_VEVIF_NEVENTS_MIN 28
#define VPRCSR_VEVIF_NEVENTS_MAX 31
#define VPRCSR_RST_UNRECOV 0
#define VPRCSR_BEXT 0
#define VPRCSR_CACHE_EN false
#define VPRCSR_OUTMODE_VPR1_2 false

/*One time programmable Information Configuration Registers*/
#define OICR_PRESENT
#define OICR_COUNT 1

/*CACHEDATA*/
#define CACHEDATA_PRESENT
#define CACHEDATA_COUNT 1

/*CACHEINFO*/
#define CACHEINFO_PRESENT
#define CACHEINFO_COUNT 1

/*CRACENCORE*/
#define CRACENCORE_PRESENT
#define CRACENCORE_COUNT 1

#define SHA3CORE_CRYPTMSTRDMAREGS true
#define SHA3CORE_CRYPTMSTRHWREGS true
#define SHA3CORE_RNGCONTROLREGS false
#define SHA3CORE_PKREGS false
#define SHA3CORE_IKGREGS false
#define SHA3CORE_RNGDATAREGS false
#define SHA3CORE_PKDATAMEMORYREGS false
#define SHA3CORE_PKUCODEREGS false
#define SHA3CORE_CRACENRESETVALUES false
#define SHA3CORE_SHA3RESETVALUES false

/*HSFLL*/
#define HSFLL_PRESENT
#define HSFLL_COUNT 3

#define HSFLL200_DITHER_32B false

#define HSFLL121_DITHER_32B false

#define HSFLL120_DITHER_32B false

/*LRCCONF*/
#define LRCCONF_PRESENT
#define LRCCONF_COUNT 3

#define LRCCONF200_POWERON true
#define LRCCONF200_RETAIN true
#define LRCCONF200_SYSTEMOFF false
#define LRCCONF200_LRCREQHFXO false
#define LRCCONF200_NCLK_MIN 0
#define LRCCONF200_NCLK_MAX 0
#define LRCCONF200_CLKCTRL true
#define LRCCONF200_NACTPD_MIN 0
#define LRCCONF200_NACTPD_MAX 7
#define LRCCONF200_PDACT false
#define LRCCONF200_NPD_MIN 0
#define LRCCONF200_NPD_MAX 7
#define LRCCONF200_OTHERON false
#define LRCCONF200_NDOMAINS_MIN 0
#define LRCCONF200_NDOMAINS_MAX 15
#define LRCCONF200_AX2XWAITSTATES false
#define LRCCONF200_POWERON_MAIN_RESET 0
#define LRCCONF200_POWERON_ACT_RESET 0
#define LRCCONF200_RETAIN_MAIN_RESET 1
#define LRCCONF200_RETAIN_ACT_RESET 1

#define LRCCONF120_POWERON true
#define LRCCONF120_RETAIN true
#define LRCCONF120_SYSTEMOFF false
#define LRCCONF120_LRCREQHFXO false
#define LRCCONF120_NCLK_MIN 0
#define LRCCONF120_NCLK_MAX 1
#define LRCCONF120_CLKCTRL true
#define LRCCONF120_NACTPD_MIN 0
#define LRCCONF120_NACTPD_MAX 1
#define LRCCONF120_PDACT true
#define LRCCONF120_NPD_MIN 0
#define LRCCONF120_NPD_MAX 7
#define LRCCONF120_OTHERON false
#define LRCCONF120_NDOMAINS_MIN 0
#define LRCCONF120_NDOMAINS_MAX 15
#define LRCCONF120_AX2XWAITSTATES true
#define LRCCONF120_POWERON_MAIN_RESET 1
#define LRCCONF120_POWERON_ACT_RESET 1
#define LRCCONF120_RETAIN_MAIN_RESET 1
#define LRCCONF120_RETAIN_ACT_RESET 1

#define LRCCONF130_POWERON true
#define LRCCONF130_RETAIN true
#define LRCCONF130_SYSTEMOFF true
#define LRCCONF130_LRCREQHFXO false
#define LRCCONF130_NCLK_MIN 0
#define LRCCONF130_NCLK_MAX 7
#define LRCCONF130_CLKCTRL false
#define LRCCONF130_NACTPD_MIN 0
#define LRCCONF130_NACTPD_MAX 0
#define LRCCONF130_PDACT true
#define LRCCONF130_NPD_MIN 0
#define LRCCONF130_NPD_MAX 10
#define LRCCONF130_OTHERON true
#define LRCCONF130_NDOMAINS_MIN 0
#define LRCCONF130_NDOMAINS_MAX 15
#define LRCCONF130_AX2XWAITSTATES false
#define LRCCONF130_POWERON_MAIN_RESET 1
#define LRCCONF130_POWERON_ACT_RESET 1
#define LRCCONF130_RETAIN_MAIN_RESET 1
#define LRCCONF130_RETAIN_ACT_RESET 1

/*VPR CLIC registers*/
#define CLIC_PRESENT
#define CLIC_COUNT 1

#define VPRCLIC_MCLICBASE 1603047424
#define VPRCLIC_IRQNUM_MIN 0
#define VPRCLIC_IRQNUM_MAX 479
#define VPRCLIC_CLIC_NTASKS_MIN 0
#define VPRCLIC_CLIC_NTASKS_MAX 31
#define VPRCLIC_CLIC_TASKS_MASK 4294963455
#define VPRCLIC_COUNTER_IRQ_NUM 32

/*VTIM CSR registers*/
#define VTIM_PRESENT
#define VTIM_COUNT 1

/*Cache*/
#define CACHE_PRESENT
#define CACHE_COUNT 1

#define L2CACHE_VIRTUALCACHE true
#define L2CACHE_FLUSH false
#define L2CACHE_CLEAN false

/*RAM Controller*/
#define RAMC_PRESENT
#define RAMC_COUNT 6

#define RAMC110_ECC false
#define RAMC110_SEC false

#define RAMC111_ECC false
#define RAMC111_SEC false

#define RAMC120_ECC false
#define RAMC120_SEC false

#define RAMC121_ECC false
#define RAMC121_SEC false

#define RAMC130_ECC false
#define RAMC130_SEC false

#define RAMC131_ECC false
#define RAMC131_SEC false

/*CRACEN*/
#define CRACEN_PRESENT
#define CRACEN_COUNT 1

#define SHA3_CRYPTOACCELERATOR false

/*PCGCSlave*/
#define PCGCSLAVE_PRESENT
#define PCGCSLAVE_COUNT 13

#define PCGCS110_PENALTYTASKS false

#define PCGCS120_PENALTYTASKS false

#define PCGCS121_PENALTYTASKS false

#define PCGCS122_PENALTYTASKS false

#define PCGCS130_PENALTYTASKS false

#define PCGCS131_PENALTYTASKS false

#define PCGCS132_PENALTYTASKS false

#define PCGCS133_PENALTYTASKS false

#define PCGCS134_PENALTYTASKS false

#define PCGCS135_PENALTYTASKS false

#define PCGCS136_PENALTYTASKS false

#define PCGCS137_PENALTYTASKS false

#define PCGCS138_PENALTYTASKS false

/*PCGC Master*/
#define PCGCMASTER_PRESENT
#define PCGCMASTER_COUNT 12

#define PCGCM110_POWERCONSUMPTIONCALC true
#define PCGCM110_SETPWRCONTHRESHOLDBASE true
#define PCGCM110_CLOCKFORCEREG true
#define PCGCM110_MASTERFORCEREG true

#define PCGCM120_POWERCONSUMPTIONCALC true
#define PCGCM120_SETPWRCONTHRESHOLDBASE true
#define PCGCM120_CLOCKFORCEREG true
#define PCGCM120_MASTERFORCEREG true

#define PCGCM121_POWERCONSUMPTIONCALC true
#define PCGCM121_SETPWRCONTHRESHOLDBASE true
#define PCGCM121_CLOCKFORCEREG true
#define PCGCM121_MASTERFORCEREG true

#define PCGCM130_POWERCONSUMPTIONCALC true
#define PCGCM130_SETPWRCONTHRESHOLDBASE true
#define PCGCM130_CLOCKFORCEREG true
#define PCGCM130_MASTERFORCEREG true

#define PCGCM131_POWERCONSUMPTIONCALC true
#define PCGCM131_SETPWRCONTHRESHOLDBASE true
#define PCGCM131_CLOCKFORCEREG true
#define PCGCM131_MASTERFORCEREG true

#define PCGCM132_POWERCONSUMPTIONCALC true
#define PCGCM132_SETPWRCONTHRESHOLDBASE true
#define PCGCM132_CLOCKFORCEREG true
#define PCGCM132_MASTERFORCEREG true

#define PCGCM133_POWERCONSUMPTIONCALC true
#define PCGCM133_SETPWRCONTHRESHOLDBASE true
#define PCGCM133_CLOCKFORCEREG true
#define PCGCM133_MASTERFORCEREG true

#define PCGCM134_POWERCONSUMPTIONCALC true
#define PCGCM134_SETPWRCONTHRESHOLDBASE true
#define PCGCM134_CLOCKFORCEREG true
#define PCGCM134_MASTERFORCEREG true

#define PCGCM135_POWERCONSUMPTIONCALC true
#define PCGCM135_SETPWRCONTHRESHOLDBASE true
#define PCGCM135_CLOCKFORCEREG true
#define PCGCM135_MASTERFORCEREG true

#define PCGCM136_POWERCONSUMPTIONCALC true
#define PCGCM136_SETPWRCONTHRESHOLDBASE true
#define PCGCM136_CLOCKFORCEREG true
#define PCGCM136_MASTERFORCEREG true

#define PCGCM137_POWERCONSUMPTIONCALC true
#define PCGCM137_SETPWRCONTHRESHOLDBASE true
#define PCGCM137_CLOCKFORCEREG true
#define PCGCM137_MASTERFORCEREG true

#define PCGCM138_POWERCONSUMPTIONCALC true
#define PCGCM138_SETPWRCONTHRESHOLDBASE true
#define PCGCM138_CLOCKFORCEREG true
#define PCGCM138_MASTERFORCEREG true

/*EXternal Memory Encryption Engine*/
#define EXMEE_PRESENT
#define EXMEE_COUNT 1

/*MVDMA performs direct-memory-accesses between memories. Data is transferred according to job descriptor lists. Each transfer has corresponding source and sink descriptor lists with matching data amounts. The lists are in memory and they contain data buffer information, address pointers, buffer sizes and data type attributes.*/
                                                                                                                                  
#define MVDMA_PRESENT
#define MVDMA_COUNT 1

/*PPIB APB registers*/
#define PPIB_PRESENT
#define PPIB_COUNT 11

/*ROM Controller*/
#define ROMC_PRESENT
#define ROMC_COUNT 1

/*Memory configuration*/
#define MEMCONF_PRESENT
#define MEMCONF_COUNT 2

#define MEMCONF120_RETTRIM true
#define MEMCONF120_REPAIR true
#define MEMCONF120_POWER true
#define MEMCONF120_RET2 true

#define MEMCONF130_RETTRIM true
#define MEMCONF130_REPAIR true
#define MEMCONF130_POWER true
#define MEMCONF130_RET2 true

/*Watchdog Timer*/
#define WDT_PRESENT
#define WDT_COUNT 3

/*GRCCONF*/
#define GRCCONF_PRESENT
#define GRCCONF_COUNT 1

/*PCRM*/
#define PCRM_PRESENT
#define PCRM_COUNT 1

/*CLOCK*/
#define CLOCK_PRESENT
#define CLOCK_COUNT 1

/*LFRC peripheral*/
#define LFRC_PRESENT
#define LFRC_COUNT 1

/*GENERIC*/
#define GENERIC_PRESENT
#define GENERIC_COUNT 4

/*LFXO peripheral*/
#define LFXO_PRESENT
#define LFXO_COUNT 1

/*FLL16M*/
#define FLL16M_PRESENT
#define FLL16M_COUNT 1

/*HFXO peripheral*/
#define HFXO_PRESENT
#define HFXO_COUNT 1

/*AUXPLL*/
#define AUXPLL_PRESENT
#define AUXPLL_COUNT 3

/*POWER*/
#define POWER_PRESENT
#define POWER_COUNT 1

#define POWER_NABBDOMAIN_MIN 0
#define POWER_NABBDOMAIN_MAX 1
#define POWER_NATBGNDCLAMP_MIN 0
#define POWER_NATBGNDCLAMP_MAX 13
#define POWER_PMICENABLE false

/*VREGMAIN peripheral*/
#define VREGMAIN_PRESENT
#define VREGMAIN_COUNT 1

/*VREGAO1V8 peripheral*/
#define VREGAO1V8_PRESENT
#define VREGAO1V8_COUNT 1

/*VREG1V0*/
#define VREG1V0_PRESENT
#define VREG1V0_COUNT 1

/*VREGAO0V8 peripheral*/
#define VREGAO0V8_PRESENT
#define VREGAO0V8_COUNT 1

/*VREGVS0V8 peripheral*/
#define VREGVS0V8_PRESENT
#define VREGVS0V8_COUNT 1

/*VREGSU peripheral*/
#define VREGSU_PRESENT
#define VREGSU_COUNT 1

/*VREGUSB peripheral*/
#define VREGUSB_PRESENT
#define VREGUSB_COUNT 1

/*AUXPM*/
#define AUXPM_PRESENT
#define AUXPM_COUNT 2

/*VREGMRAM peripheral*/
#define VREGMRAM_PRESENT
#define VREGMRAM_COUNT 2

/*OSCRFR peripheral*/
#define OSCRFR_PRESENT
#define OSCRFR_COUNT 1

/*SWEXT peripheral*/
#define SWEXT_PRESENT
#define SWEXT_COUNT 1

/*MBIAS peripheral*/
#define MBIAS_PRESENT
#define MBIAS_COUNT 1

/*VDETAO1V8 peripheral*/
#define VDETAO1V8_PRESENT
#define VDETAO1V8_COUNT 1

/*VDETAO0V8 peripheral*/
#define VDETAO0V8_PRESENT
#define VDETAO0V8_COUNT 1

/*VDETVS0V8 peripheral*/
#define VDETVS0V8_PRESENT
#define VDETVS0V8_COUNT 1

/*VDETIO peripheral*/
#define VDETIO_PRESENT
#define VDETIO_COUNT 1

/*VDETAO5V0 peripheral*/
#define VDETAO5V0_PRESENT
#define VDETAO5V0_COUNT 1

/*VDET1V0 peripheral*/
#define VDET1V0_PRESENT
#define VDET1V0_COUNT 1

/*Factory Information Configuration Registers*/
#define FICR_PRESENT
#define FICR_COUNT 1

#define FICR_LTE_ON false
#define FICR_WIFI_ON false
#define FICR_NFC_ON true

/*USBHSCORE*/
#define USBHSCORE_PRESENT
#define USBHSCORE_COUNT 1

/*I3CCORE*/
#define I3CCORE_PRESENT
#define I3CCORE_COUNT 2

/*System Trace Macrocell data buffer*/
#define STMDATA_PRESENT
#define STMDATA_COUNT 1

/*TDDCONF*/
#define TDDCONF_PRESENT
#define TDDCONF_COUNT 1

/*System Trace Macrocell*/
#define STM_PRESENT
#define STM_COUNT 1

/*Trace Port Interface Unit*/
#define TPIU_PRESENT
#define TPIU_COUNT 1

/*Cross-Trigger Interface control*/
#define CTI_PRESENT
#define CTI_COUNT 2

/*ATB Replicator module*/
#define ATBREPLICATOR_PRESENT
#define ATBREPLICATOR_COUNT 4

/*ATB funnel module*/
#define ATBFUNNEL_PRESENT
#define ATBFUNNEL_COUNT 4

/*GPIO Tasks and Events*/
#define GPIOTE_PRESENT
#define GPIOTE_COUNT 1

/*Global Real-time counter*/
#define GRTC_PRESENT
#define GRTC_COUNT 1

#define GRTC_MSBWIDTH_MIN 0
#define GRTC_MSBWIDTH_MAX 14
#define GRTC_NCC_MIN 0
#define GRTC_NCC_MAX 15
#define GRTC_NTIMEOUT_MIN 0
#define GRTC_NTIMEOUT_MAX 15
#define GRTC_NDOMAIN_MIN 0
#define GRTC_NDOMAIN_MAX 15
#define GRTC_GRTC_NINTERRUPTS_MIN 0
#define GRTC_GRTC_NINTERRUPTS_MAX 1
#define GRTC_PWMREGS false
#define GRTC_CLKOUTREG false

/*Trace buffer monitor*/
#define TBM_PRESENT
#define TBM_COUNT 1

/*USBHS*/
#define USBHS_PRESENT
#define USBHS_COUNT 1

/*MRAM controller*/
#define MRAMC_PRESENT
#define MRAMC_COUNT 2

#define MRAMC110_NMRAMWORDSIZE 128
#define MRAMC110_NMRAMPAGESIZE 4
#define MRAMC110_NNVRPAGESIZE 2
#define MRAMC110_NMAINMEMORYSIZE 1
#define MRAMC110_NNVRPAGES_MIN 0
#define MRAMC110_NNVRPAGES_MAX 3
#define MRAMC110_NSIZEMRAMWORDS_MIN 1
#define MRAMC110_NSIZEMRAMWORDS_MAX 65536
#define MRAMC110_MARMDATAWIDTHWORDS_MIN 0
#define MRAMC110_MARMDATAWIDTHWORDS_MAX 3
#define MRAMC110_NVRPAGEUPPER false
#define MRAMC110_NVRPAGELOWER false

#define MRAMC111_NMRAMWORDSIZE 128
#define MRAMC111_NMRAMPAGESIZE 4
#define MRAMC111_NNVRPAGESIZE 2
#define MRAMC111_NMAINMEMORYSIZE 1
#define MRAMC111_NNVRPAGES_MIN 0
#define MRAMC111_NNVRPAGES_MAX 3
#define MRAMC111_NSIZEMRAMWORDS_MIN 1
#define MRAMC111_NSIZEMRAMWORDS_MAX 65536
#define MRAMC111_MARMDATAWIDTHWORDS_MIN 0
#define MRAMC111_MARMDATAWIDTHWORDS_MAX 3
#define MRAMC111_NVRPAGEUPPER false
#define MRAMC111_NVRPAGELOWER false

/*External Memory Interface*/
#define EXMIF_PRESENT
#define EXMIF_COUNT 1

/*OTP controller*/
#define OTPC_PRESENT
#define OTPC_COUNT 1

#define OTPC_REGION_NO_EXTENSION true
#define OTPC_REGION_EXTENSION false
#define OTPC_NREGIONS_MIN 0
#define OTPC_NREGIONS_MAX 5
#define OTPC_REGION0ADDR 797179904
#define OTPC_REGION0SIZE 1024
#define OTPC_REGION1ADDR 797180928
#define OTPC_REGION1SIZE 15360
#define OTPC_REGION2ADDR 0
#define OTPC_REGION2SIZE 0
#define OTPC_REGION3ADDR 0
#define OTPC_REGION3SIZE 0
#define OTPC_REGION4ADDR 0
#define OTPC_REGION4SIZE 0
#define OTPC_REGION5ADDR 0
#define OTPC_REGION5SIZE 0

/*VPR peripheral registers*/
#define VPR_PRESENT
#define VPR_COUNT 3

#define VPR120_INIT_PC_RESET_VALUE 796917760
#define VPR120_VPR_START_RESET_VALUE 1
#define VPR120_RAM_BASE_ADDR 796917760
#define VPR120_RAM_SZ 16
#define VPR120_VPRSAVEDCTX_REGNAME NRF_MEMCONF120->POWER[0].RET
#define VPR120_VPRSAVEDCTX_REGBIT 22
#define VPR120_RETAINED 0
#define VPR120_VPRSAVEDCTX true
#define VPR120_VPRSAVEADDR 796917760
#define VPR120_VPRREMAPADDRVTOB 797179904
#define VPR120_VEVIF_NTASKS_MIN 0
#define VPR120_VEVIF_NTASKS_MAX 31
#define VPR120_VEVIF_TASKS_MASK 4294963455
#define VPR120_VEVIF_NDPPI_MIN 24
#define VPR120_VEVIF_NDPPI_MAX 27
#define VPR120_VEVIF_NEVENTS_MIN 28
#define VPR120_VEVIF_NEVENTS_MAX 31
#define VPR120_DEBUGGER_OFFSET 1024

#define VPR121_INIT_PC_RESET_VALUE 0
#define VPR121_VPR_START_RESET_VALUE 0
#define VPR121_RAM_BASE_ADDR 797507584
#define VPR121_RAM_SZ 15
#define VPR121_VPRSAVEDCTX_REGNAME NRF_MEMCONF120->POWER[0].RET
#define VPR121_VPRSAVEDCTX_REGBIT 23
#define VPR121_RETAINED 0
#define VPR121_VPRSAVEDCTX true
#define VPR121_VPRSAVEADDR 796917760
#define VPR121_VPRREMAPADDRVTOB 0
#define VPR121_VEVIF_NTASKS_MIN 0
#define VPR121_VEVIF_NTASKS_MAX 31
#define VPR121_VEVIF_TASKS_MASK 4294901760
#define VPR121_VEVIF_NDPPI_MIN 24
#define VPR121_VEVIF_NDPPI_MAX 27
#define VPR121_VEVIF_NEVENTS_MIN 28
#define VPR121_VEVIF_NEVENTS_MAX 31
#define VPR121_DEBUGGER_OFFSET 1024

#define VPR130_INIT_PC_RESET_VALUE 0
#define VPR130_VPR_START_RESET_VALUE 0
#define VPR130_RAM_BASE_ADDR 801112064
#define VPR130_RAM_SZ 15
#define VPR130_VPRSAVEDCTX_REGNAME NRF_MEMCONF130->POWER[0].RET
#define VPR130_VPRSAVEDCTX_REGBIT 5
#define VPR130_RETAINED 0
#define VPR130_VPRSAVEDCTX true
#define VPR130_VPRSAVEADDR 796917760
#define VPR130_VPRREMAPADDRVTOB 0
#define VPR130_VEVIF_NTASKS_MIN 0
#define VPR130_VEVIF_NTASKS_MAX 15
#define VPR130_VEVIF_TASKS_MASK 4294967280
#define VPR130_VEVIF_NDPPI_MIN 8
#define VPR130_VEVIF_NDPPI_MAX 11
#define VPR130_VEVIF_NEVENTS_MIN 12
#define VPR130_VEVIF_NEVENTS_MAX 15
#define VPR130_DEBUGGER_OFFSET 1024

/*IPCT APB registers*/
#define IPCT_PRESENT
#define IPCT_COUNT 2

/*MUTEX*/
#define MUTEX_PRESENT
#define MUTEX_COUNT 2

/*I3C*/
#define I3C_PRESENT
#define I3C_COUNT 2

/*Controller Area Network*/
#define CAN_PRESENT
#define CAN_COUNT 1

/*Distributed programmable peripheral interconnect controller*/
#define DPPIC_PRESENT
#define DPPIC_COUNT 8

#define DPPIC120_HASCHANNELGROUPS true
#define DPPIC120_CH_NUM_MIN 0
#define DPPIC120_CH_NUM_MAX 7
#define DPPIC120_GROUP_NUM_MIN 0
#define DPPIC120_GROUP_NUM_MAX 1

#define DPPIC130_HASCHANNELGROUPS true
#define DPPIC130_CH_NUM_MIN 0
#define DPPIC130_CH_NUM_MAX 7
#define DPPIC130_GROUP_NUM_MIN 0
#define DPPIC130_GROUP_NUM_MAX 1

#define DPPIC131_HASCHANNELGROUPS true
#define DPPIC131_CH_NUM_MIN 0
#define DPPIC131_CH_NUM_MAX 7
#define DPPIC131_GROUP_NUM_MIN 0
#define DPPIC131_GROUP_NUM_MAX 1

#define DPPIC132_HASCHANNELGROUPS true
#define DPPIC132_CH_NUM_MIN 0
#define DPPIC132_CH_NUM_MAX 7
#define DPPIC132_GROUP_NUM_MIN 0
#define DPPIC132_GROUP_NUM_MAX 1

#define DPPIC133_HASCHANNELGROUPS true
#define DPPIC133_CH_NUM_MIN 0
#define DPPIC133_CH_NUM_MAX 7
#define DPPIC133_GROUP_NUM_MIN 0
#define DPPIC133_GROUP_NUM_MAX 1

#define DPPIC134_HASCHANNELGROUPS true
#define DPPIC134_CH_NUM_MIN 0
#define DPPIC134_CH_NUM_MAX 7
#define DPPIC134_GROUP_NUM_MIN 0
#define DPPIC134_GROUP_NUM_MAX 1

#define DPPIC135_HASCHANNELGROUPS true
#define DPPIC135_CH_NUM_MIN 0
#define DPPIC135_CH_NUM_MAX 7
#define DPPIC135_GROUP_NUM_MIN 0
#define DPPIC135_GROUP_NUM_MAX 1

#define DPPIC136_HASCHANNELGROUPS true
#define DPPIC136_CH_NUM_MIN 0
#define DPPIC136_CH_NUM_MAX 7
#define DPPIC136_GROUP_NUM_MIN 0
#define DPPIC136_GROUP_NUM_MAX 1

/*Timer/Counter*/
#define TIMER_PRESENT
#define TIMER_COUNT 10

#define TIMER120_CC_NUM_MIN 0
#define TIMER120_CC_NUM_MAX 5
#define TIMER120_MAX_SIZE_MIN 0
#define TIMER120_MAX_SIZE_MAX 31

#define TIMER121_CC_NUM_MIN 0
#define TIMER121_CC_NUM_MAX 5
#define TIMER121_MAX_SIZE_MIN 0
#define TIMER121_MAX_SIZE_MAX 31

#define TIMER130_CC_NUM_MIN 0
#define TIMER130_CC_NUM_MAX 5
#define TIMER130_MAX_SIZE_MIN 0
#define TIMER130_MAX_SIZE_MAX 31

#define TIMER131_CC_NUM_MIN 0
#define TIMER131_CC_NUM_MAX 5
#define TIMER131_MAX_SIZE_MIN 0
#define TIMER131_MAX_SIZE_MAX 31

#define TIMER132_CC_NUM_MIN 0
#define TIMER132_CC_NUM_MAX 5
#define TIMER132_MAX_SIZE_MIN 0
#define TIMER132_MAX_SIZE_MAX 31

#define TIMER133_CC_NUM_MIN 0
#define TIMER133_CC_NUM_MAX 5
#define TIMER133_MAX_SIZE_MIN 0
#define TIMER133_MAX_SIZE_MAX 31

#define TIMER134_CC_NUM_MIN 0
#define TIMER134_CC_NUM_MAX 5
#define TIMER134_MAX_SIZE_MIN 0
#define TIMER134_MAX_SIZE_MAX 31

#define TIMER135_CC_NUM_MIN 0
#define TIMER135_CC_NUM_MAX 5
#define TIMER135_MAX_SIZE_MIN 0
#define TIMER135_MAX_SIZE_MAX 31

#define TIMER136_CC_NUM_MIN 0
#define TIMER136_CC_NUM_MAX 5
#define TIMER136_MAX_SIZE_MIN 0
#define TIMER136_MAX_SIZE_MAX 31

#define TIMER137_CC_NUM_MIN 0
#define TIMER137_CC_NUM_MAX 5
#define TIMER137_MAX_SIZE_MIN 0
#define TIMER137_MAX_SIZE_MAX 31

/*Pulse width modulation unit*/
#define PWM_PRESENT
#define PWM_COUNT 5

#define PWM120_EASYDMA5 false
#define PWM120_EASYDMATEMP true

#define PWM130_EASYDMA5 false
#define PWM130_EASYDMATEMP true

#define PWM131_EASYDMA5 false
#define PWM131_EASYDMATEMP true

#define PWM132_EASYDMA5 false
#define PWM132_EASYDMATEMP true

#define PWM133_EASYDMA5 false
#define PWM133_EASYDMATEMP true

/*SPI Slave*/
#define SPIS_PRESENT
#define SPIS_COUNT 9

#define SPIS120_LEGACYPSEL false
#define SPIS120_LEGACYEDMA false
#define SPIS120_EASYDMA5 false
#define SPIS120_EASYDMATEMP true
#define SPIS120_EASYDMALISTINCLUDED false
#define SPIS120_EASYDMAMODEINCLUDED false
#define SPIS120_EASYDMAFULLLPMODEINCLUDED false

#define SPIS130_LEGACYPSEL false
#define SPIS130_LEGACYEDMA false
#define SPIS130_EASYDMA5 false
#define SPIS130_EASYDMATEMP true
#define SPIS130_EASYDMALISTINCLUDED false
#define SPIS130_EASYDMAMODEINCLUDED false
#define SPIS130_EASYDMAFULLLPMODEINCLUDED false

#define SPIS131_LEGACYPSEL false
#define SPIS131_LEGACYEDMA false
#define SPIS131_EASYDMA5 false
#define SPIS131_EASYDMATEMP true
#define SPIS131_EASYDMALISTINCLUDED false
#define SPIS131_EASYDMAMODEINCLUDED false
#define SPIS131_EASYDMAFULLLPMODEINCLUDED false

#define SPIS132_LEGACYPSEL false
#define SPIS132_LEGACYEDMA false
#define SPIS132_EASYDMA5 false
#define SPIS132_EASYDMATEMP true
#define SPIS132_EASYDMALISTINCLUDED false
#define SPIS132_EASYDMAMODEINCLUDED false
#define SPIS132_EASYDMAFULLLPMODEINCLUDED false

#define SPIS133_LEGACYPSEL false
#define SPIS133_LEGACYEDMA false
#define SPIS133_EASYDMA5 false
#define SPIS133_EASYDMATEMP true
#define SPIS133_EASYDMALISTINCLUDED false
#define SPIS133_EASYDMAMODEINCLUDED false
#define SPIS133_EASYDMAFULLLPMODEINCLUDED false

#define SPIS134_LEGACYPSEL false
#define SPIS134_LEGACYEDMA false
#define SPIS134_EASYDMA5 false
#define SPIS134_EASYDMATEMP true
#define SPIS134_EASYDMALISTINCLUDED false
#define SPIS134_EASYDMAMODEINCLUDED false
#define SPIS134_EASYDMAFULLLPMODEINCLUDED false

#define SPIS135_LEGACYPSEL false
#define SPIS135_LEGACYEDMA false
#define SPIS135_EASYDMA5 false
#define SPIS135_EASYDMATEMP true
#define SPIS135_EASYDMALISTINCLUDED false
#define SPIS135_EASYDMAMODEINCLUDED false
#define SPIS135_EASYDMAFULLLPMODEINCLUDED false

#define SPIS136_LEGACYPSEL false
#define SPIS136_LEGACYEDMA false
#define SPIS136_EASYDMA5 false
#define SPIS136_EASYDMATEMP true
#define SPIS136_EASYDMALISTINCLUDED false
#define SPIS136_EASYDMAMODEINCLUDED false
#define SPIS136_EASYDMAFULLLPMODEINCLUDED false

#define SPIS137_LEGACYPSEL false
#define SPIS137_LEGACYEDMA false
#define SPIS137_EASYDMA5 false
#define SPIS137_EASYDMATEMP true
#define SPIS137_EASYDMALISTINCLUDED false
#define SPIS137_EASYDMAMODEINCLUDED false
#define SPIS137_EASYDMAFULLLPMODEINCLUDED false

/*UART with EasyDMA*/
#define UARTE_PRESENT
#define UARTE_COUNT 9

#define UARTE120_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE120_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE120_EASYDMA5 false
#define UARTE120_EASYDMATEMP true
#define UARTE120_EASYDMALISTINCLUDED false
#define UARTE120_EASYDMAMODEINCLUDED false
#define UARTE120_EASYDMAFULLLPMODEINCLUDED false

#define UARTE130_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE130_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE130_EASYDMA5 false
#define UARTE130_EASYDMATEMP true
#define UARTE130_EASYDMALISTINCLUDED false
#define UARTE130_EASYDMAMODEINCLUDED false
#define UARTE130_EASYDMAFULLLPMODEINCLUDED false

#define UARTE131_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE131_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE131_EASYDMA5 false
#define UARTE131_EASYDMATEMP true
#define UARTE131_EASYDMALISTINCLUDED false
#define UARTE131_EASYDMAMODEINCLUDED false
#define UARTE131_EASYDMAFULLLPMODEINCLUDED false

#define UARTE132_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE132_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE132_EASYDMA5 false
#define UARTE132_EASYDMATEMP true
#define UARTE132_EASYDMALISTINCLUDED false
#define UARTE132_EASYDMAMODEINCLUDED false
#define UARTE132_EASYDMAFULLLPMODEINCLUDED false

#define UARTE133_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE133_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE133_EASYDMA5 false
#define UARTE133_EASYDMATEMP true
#define UARTE133_EASYDMALISTINCLUDED false
#define UARTE133_EASYDMAMODEINCLUDED false
#define UARTE133_EASYDMAFULLLPMODEINCLUDED false

#define UARTE134_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE134_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE134_EASYDMA5 false
#define UARTE134_EASYDMATEMP true
#define UARTE134_EASYDMALISTINCLUDED false
#define UARTE134_EASYDMAMODEINCLUDED false
#define UARTE134_EASYDMAFULLLPMODEINCLUDED false

#define UARTE135_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE135_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE135_EASYDMA5 false
#define UARTE135_EASYDMATEMP true
#define UARTE135_EASYDMALISTINCLUDED false
#define UARTE135_EASYDMAMODEINCLUDED false
#define UARTE135_EASYDMAFULLLPMODEINCLUDED false

#define UARTE136_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE136_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE136_EASYDMA5 false
#define UARTE136_EASYDMATEMP true
#define UARTE136_EASYDMALISTINCLUDED false
#define UARTE136_EASYDMAMODEINCLUDED false
#define UARTE136_EASYDMAFULLLPMODEINCLUDED false

#define UARTE137_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE137_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE137_EASYDMA5 false
#define UARTE137_EASYDMATEMP true
#define UARTE137_EASYDMALISTINCLUDED false
#define UARTE137_EASYDMAMODEINCLUDED false
#define UARTE137_EASYDMAFULLLPMODEINCLUDED false

/*Serial Peripheral Interface Master with EasyDMA*/
#define SPIM_PRESENT
#define SPIM_COUNT 10

#define SPIM120_EASYDMA5 false
#define SPIM120_EASYDMATEMP true
#define SPIM120_EASYDMALISTINCLUDED false
#define SPIM120_EASYDMAMODEINCLUDED false
#define SPIM120_EASYDMAFULLLPMODEINCLUDED false
#define SPIM120_HSSPI true

#define SPIM121_EASYDMA5 false
#define SPIM121_EASYDMATEMP true
#define SPIM121_EASYDMALISTINCLUDED false
#define SPIM121_EASYDMAMODEINCLUDED false
#define SPIM121_EASYDMAFULLLPMODEINCLUDED false
#define SPIM121_HSSPI true

#define SPIM130_EASYDMA5 false
#define SPIM130_EASYDMATEMP true
#define SPIM130_EASYDMALISTINCLUDED false
#define SPIM130_EASYDMAMODEINCLUDED false
#define SPIM130_EASYDMAFULLLPMODEINCLUDED false
#define SPIM130_HSSPI true

#define SPIM131_EASYDMA5 false
#define SPIM131_EASYDMATEMP true
#define SPIM131_EASYDMALISTINCLUDED false
#define SPIM131_EASYDMAMODEINCLUDED false
#define SPIM131_EASYDMAFULLLPMODEINCLUDED false
#define SPIM131_HSSPI true

#define SPIM132_EASYDMA5 false
#define SPIM132_EASYDMATEMP true
#define SPIM132_EASYDMALISTINCLUDED false
#define SPIM132_EASYDMAMODEINCLUDED false
#define SPIM132_EASYDMAFULLLPMODEINCLUDED false
#define SPIM132_HSSPI true

#define SPIM133_EASYDMA5 false
#define SPIM133_EASYDMATEMP true
#define SPIM133_EASYDMALISTINCLUDED false
#define SPIM133_EASYDMAMODEINCLUDED false
#define SPIM133_EASYDMAFULLLPMODEINCLUDED false
#define SPIM133_HSSPI true

#define SPIM134_EASYDMA5 false
#define SPIM134_EASYDMATEMP true
#define SPIM134_EASYDMALISTINCLUDED false
#define SPIM134_EASYDMAMODEINCLUDED false
#define SPIM134_EASYDMAFULLLPMODEINCLUDED false
#define SPIM134_HSSPI true

#define SPIM135_EASYDMA5 false
#define SPIM135_EASYDMATEMP true
#define SPIM135_EASYDMALISTINCLUDED false
#define SPIM135_EASYDMAMODEINCLUDED false
#define SPIM135_EASYDMAFULLLPMODEINCLUDED false
#define SPIM135_HSSPI true

#define SPIM136_EASYDMA5 false
#define SPIM136_EASYDMATEMP true
#define SPIM136_EASYDMALISTINCLUDED false
#define SPIM136_EASYDMAMODEINCLUDED false
#define SPIM136_EASYDMAFULLLPMODEINCLUDED false
#define SPIM136_HSSPI true

#define SPIM137_EASYDMA5 false
#define SPIM137_EASYDMATEMP true
#define SPIM137_EASYDMALISTINCLUDED false
#define SPIM137_EASYDMAMODEINCLUDED false
#define SPIM137_EASYDMAFULLLPMODEINCLUDED false
#define SPIM137_HSSPI true

/*Real-time counter*/
#define RTC_PRESENT
#define RTC_COUNT 2

/*GPIO Port*/
#define GPIO_PRESENT
#define GPIO_COUNT 16

#define P0_DRIVECTRL false
#define P0_PWRCTRL false

#define P1_DRIVECTRL false
#define P1_PWRCTRL false

#define P2_DRIVECTRL false
#define P2_PWRCTRL false

#define P3_DRIVECTRL false
#define P3_PWRCTRL false

#define P4_DRIVECTRL false
#define P4_PWRCTRL false

#define P5_DRIVECTRL false
#define P5_PWRCTRL false

#define P6_DRIVECTRL true
#define P6_PWRCTRL false

#define P7_DRIVECTRL true
#define P7_PWRCTRL false

#define P8_DRIVECTRL true
#define P8_PWRCTRL false

#define P9_DRIVECTRL false
#define P9_PWRCTRL true

#define P10_DRIVECTRL false
#define P10_PWRCTRL false

#define P11_DRIVECTRL false
#define P11_PWRCTRL false

#define P12_DRIVECTRL false
#define P12_PWRCTRL false

#define P13_DRIVECTRL false
#define P13_PWRCTRL false

#define P14_DRIVECTRL false
#define P14_PWRCTRL false

#define P15_DRIVECTRL false
#define P15_PWRCTRL false

/*GPIO Internal*/
#define GPIOINTERNAL_PRESENT
#define GPIOINTERNAL_COUNT 1

/*Reset hub*/
#define RESETHUB_PRESENT
#define RESETHUB_COUNT 1

/*Analog to Digital Converter*/
#define SAADC_PRESENT
#define SAADC_COUNT 1

#define SAADC_EASYDMA5 false
#define SAADC_EASYDMATEMP true
#define SAADC_EASYDMALISTINCLUDED false
#define SAADC_EASYDMAMODEINCLUDED false
#define SAADC_EASYDMAFULLLPMODEINCLUDED false

/*Comparator*/
#define COMP_PRESENT
#define COMP_COUNT 1

/*Low-power comparator*/
#define LPCOMP_PRESENT
#define LPCOMP_COUNT 1

/*Temperature Sensor*/
#define TEMP_PRESENT
#define TEMP_COUNT 1

/*NFC-A compatible radio NFC-A compatible radio*/
#define NFCT_PRESENT
#define NFCT_COUNT 1

#define NFCT_EASYDMA5 false
#define NFCT_EASYDMATEMP false

/*Inter-IC Sound*/
#define I2S_PRESENT
#define I2S_COUNT 2

/*Pulse Density Modulation (Digital Microphone) Interface*/
#define PDM_PRESENT
#define PDM_COUNT 1

#define PDM_EASYDMA5 false
#define PDM_EASYDMATEMP true
#define PDM_EASYDMALISTINCLUDED false
#define PDM_EASYDMAMODEINCLUDED false
#define PDM_EASYDMAFULLLPMODEINCLUDED false

/*Quadrature Decoder*/
#define QDEC_PRESENT
#define QDEC_COUNT 2

#define QDEC130_LEGACYPSEL false

#define QDEC131_LEGACYPSEL false

/*SIM card interface*/
#define SIMIF_PRESENT
#define SIMIF_COUNT 1

/*I2C compatible Two-Wire Master Interface with EasyDMA*/
#define TWIM_PRESENT
#define TWIM_COUNT 8

#define TWIM130_EASYDMA5 false
#define TWIM130_EASYDMATEMP true
#define TWIM130_EASYDMALISTINCLUDED false
#define TWIM130_EASYDMAMODEINCLUDED false
#define TWIM130_EASYDMAFULLLPMODEINCLUDED false

#define TWIM131_EASYDMA5 false
#define TWIM131_EASYDMATEMP true
#define TWIM131_EASYDMALISTINCLUDED false
#define TWIM131_EASYDMAMODEINCLUDED false
#define TWIM131_EASYDMAFULLLPMODEINCLUDED false

#define TWIM132_EASYDMA5 false
#define TWIM132_EASYDMATEMP true
#define TWIM132_EASYDMALISTINCLUDED false
#define TWIM132_EASYDMAMODEINCLUDED false
#define TWIM132_EASYDMAFULLLPMODEINCLUDED false

#define TWIM133_EASYDMA5 false
#define TWIM133_EASYDMATEMP true
#define TWIM133_EASYDMALISTINCLUDED false
#define TWIM133_EASYDMAMODEINCLUDED false
#define TWIM133_EASYDMAFULLLPMODEINCLUDED false

#define TWIM134_EASYDMA5 false
#define TWIM134_EASYDMATEMP true
#define TWIM134_EASYDMALISTINCLUDED false
#define TWIM134_EASYDMAMODEINCLUDED false
#define TWIM134_EASYDMAFULLLPMODEINCLUDED false

#define TWIM135_EASYDMA5 false
#define TWIM135_EASYDMATEMP true
#define TWIM135_EASYDMALISTINCLUDED false
#define TWIM135_EASYDMAMODEINCLUDED false
#define TWIM135_EASYDMAFULLLPMODEINCLUDED false

#define TWIM136_EASYDMA5 false
#define TWIM136_EASYDMATEMP true
#define TWIM136_EASYDMALISTINCLUDED false
#define TWIM136_EASYDMAMODEINCLUDED false
#define TWIM136_EASYDMAFULLLPMODEINCLUDED false

#define TWIM137_EASYDMA5 false
#define TWIM137_EASYDMATEMP true
#define TWIM137_EASYDMALISTINCLUDED false
#define TWIM137_EASYDMAMODEINCLUDED false
#define TWIM137_EASYDMAFULLLPMODEINCLUDED false

/*I2C compatible Two-Wire Slave Interface with EasyDMA*/
#define TWIS_PRESENT
#define TWIS_COUNT 8

#define TWIS130_EASYDMA5 false
#define TWIS130_EASYDMATEMP true
#define TWIS130_EASYDMALISTINCLUDED false
#define TWIS130_EASYDMAMODEINCLUDED false
#define TWIS130_EASYDMAFULLLPMODEINCLUDED false

#define TWIS131_EASYDMA5 false
#define TWIS131_EASYDMATEMP true
#define TWIS131_EASYDMALISTINCLUDED false
#define TWIS131_EASYDMAMODEINCLUDED false
#define TWIS131_EASYDMAFULLLPMODEINCLUDED false

#define TWIS132_EASYDMA5 false
#define TWIS132_EASYDMATEMP true
#define TWIS132_EASYDMALISTINCLUDED false
#define TWIS132_EASYDMAMODEINCLUDED false
#define TWIS132_EASYDMAFULLLPMODEINCLUDED false

#define TWIS133_EASYDMA5 false
#define TWIS133_EASYDMATEMP true
#define TWIS133_EASYDMALISTINCLUDED false
#define TWIS133_EASYDMAMODEINCLUDED false
#define TWIS133_EASYDMAFULLLPMODEINCLUDED false

#define TWIS134_EASYDMA5 false
#define TWIS134_EASYDMATEMP true
#define TWIS134_EASYDMALISTINCLUDED false
#define TWIS134_EASYDMAMODEINCLUDED false
#define TWIS134_EASYDMAFULLLPMODEINCLUDED false

#define TWIS135_EASYDMA5 false
#define TWIS135_EASYDMATEMP true
#define TWIS135_EASYDMALISTINCLUDED false
#define TWIS135_EASYDMAMODEINCLUDED false
#define TWIS135_EASYDMAFULLLPMODEINCLUDED false

#define TWIS136_EASYDMA5 false
#define TWIS136_EASYDMATEMP true
#define TWIS136_EASYDMALISTINCLUDED false
#define TWIS136_EASYDMAMODEINCLUDED false
#define TWIS136_EASYDMAFULLLPMODEINCLUDED false

#define TWIS137_EASYDMA5 false
#define TWIS137_EASYDMATEMP true
#define TWIS137_EASYDMALISTINCLUDED false
#define TWIS137_EASYDMAMODEINCLUDED false
#define TWIS137_EASYDMAFULLLPMODEINCLUDED false


#ifdef __cplusplus
}
#endif
#endif /* NRF54H20_ENGA_SYSCTRL_PERIPHERALS_H */

