/*

Copyright (c) 2010 - 2024, Nordic Semiconductor ASA

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form, except as embedded into a Nordic
   Semiconductor ASA integrated circuit in a product or a software update for
   such product, must reproduce the above copyright notice, this list of
   conditions and the following disclaimer in the documentation and/or other
   materials provided with the distribution.

3. Neither the name of Nordic Semiconductor ASA nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

4. This software, with or without modification, must only be used with a
   Nordic Semiconductor ASA integrated circuit.

5. Any software provided in binary form under this license must not be reverse
   engineered, decompiled, modified and/or disassembled.

THIS SOFTWARE IS PROVIDED BY NORDIC SEMICONDUCTOR ASA "AS IS" AND ANY EXPRESS
OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY, NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL NORDIC SEMICONDUCTOR ASA OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#ifndef NRF54L15_ENGA_NAME_CHANGE_H
#define NRF54L15_ENGA_NAME_CHANGE_H

#ifdef __cplusplus
    extern "C" {
#endif

#define NRF_GLITCHDET_GLITCHDETECTOR_DFT_Type NRF_GLITCHDET_DFT_Type
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB0CONFIG_ResetValue GLITCHDET_DFT_ATB0CONFIG_ResetValue

#define GLITCHDET_GLITCHDETECTOR_DFT_ATB0CONFIG_SELMUX_Pos  GLITCHDET_DFT_ATB0CONFIG_SELMUX_Pos
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB0CONFIG_SELMUX_Msk GLITCHDET_DFT_ATB0CONFIG_SELMUX_Msk
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB0CONFIG_SELMUX_Min GLITCHDET_DFT_ATB0CONFIG_SELMUX_Min
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB0CONFIG_SELMUX_Max GLITCHDET_DFT_ATB0CONFIG_SELMUX_Max
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB0CONFIG_SELMUX_HiZ GLITCHDET_DFT_ATB0CONFIG_SELMUX_HiZ
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB0CONFIG_SELMUX_VDDDIV  GLITCHDET_DFT_ATB0CONFIG_SELMUX_VDDDIV
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB0CONFIG_SELMUX_VDDDIG0V9 GLITCHDET_DFT_ATB0CONFIG_SELMUX_VDDDIG0V9
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB0CONFIG_SELMUX_VSS GLITCHDET_DFT_ATB0CONFIG_SELMUX_VSS
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB0CONFIG_SELMUX_GLITCHSRVDD3V0 GLITCHDET_DFT_ATB0CONFIG_SELMUX_GLITCHSRVDD3V0

#define GLITCHDET_GLITCHDETECTOR_DFT_ATB1CONFIG_ResetValue GLITCHDET_DFT_ATB1CONFIG_ResetValue


#define GLITCHDET_GLITCHDETECTOR_DFT_ATB1CONFIG_SELMUX_Pos GLITCHDET_DFT_ATB1CONFIG_SELMUX_Pos
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB1CONFIG_SELMUX_Msk GLITCHDET_DFT_ATB1CONFIG_SELMUX_Msk
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB1CONFIG_SELMUX_Min GLITCHDET_DFT_ATB1CONFIG_SELMUX_Min
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB1CONFIG_SELMUX_Max GLITCHDET_DFT_ATB1CONFIG_SELMUX_Max
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB1CONFIG_SELMUX_HiZ GLITCHDET_DFT_ATB1CONFIG_SELMUX_HiZ
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB1CONFIG_SELMUX_VREFHVDD GLITCHDET_DFT_ATB1CONFIG_SELMUX_VREFHVDD
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB1CONFIG_SELMUX_VREFLVDD GLITCHDET_DFT_ATB1CONFIG_SELMUX_VREFLVDD
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB1CONFIG_SELMUX_VREFHDAVDD GLITCHDET_DFT_ATB1CONFIG_SELMUX_VREFHDAVDD
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB1CONFIG_SELMUX_VREFLDVDD GLITCHDET_DFT_ATB1CONFIG_SELMUX_VREFLDVDD
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB1CONFIG_SELMUX_GLITCHSRDVDD3V0 GLITCHDET_DFT_ATB1CONFIG_SELMUX_GLITCHSRDVDD3V0

#define GLITCHDET_GLITCHDETECTOR_DFT_ATB2CONFIG_SELMUX_Pos GLITCHDET_DFT_ATB2CONFIG_SELMUX_Pos
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB2CONFIG_SELMUX_Msk GLITCHDET_DFT_ATB2CONFIG_SELMUX_Msk
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB2CONFIG_SELMUX_Min GLITCHDET_DFT_ATB2CONFIG_SELMUX_Min
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB2CONFIG_SELMUX_Max GLITCHDET_DFT_ATB2CONFIG_SELMUX_Max
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB2CONFIG_SELMUX_HiZ GLITCHDET_DFT_ATB2CONFIG_SELMUX_HiZ
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB2CONFIG_SELMUX_VTAMPORDVDD3V0 GLITCHDET_DFT_ATB2CONFIG_SELMUX_VTAMPORDVDD3V0
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB2CONFIG_SELMUX_VTAMPORVDD3V0 GLITCHDET_DFT_ATB2CONFIG_SELMUX_VTAMPORVDD3V0
#define GLITCHDET_GLITCHDETECTOR_DFT_ATB2CONFIG_SELMUX_GLITCHNINT3V0 GLITCHDET_DFT_ATB2CONFIG_SELMUX_GLITCHNINT3V0


#define GLITCHDET_GLITCHDETECTOR_CONFIG_ResetValue GLITCHDET_CONFIG_ResetValue

#define GLITCHDET_GLITCHDETECTOR_CONFIG_ENABLE_Pos GLITCHDET_CONFIG_ENABLE_Pos  
#define GLITCHDET_GLITCHDETECTOR_CONFIG_ENABLE_Msk GLITCHDET_CONFIG_ENABLE_Msk                       
#define GLITCHDET_GLITCHDETECTOR_CONFIG_ENABLE_Min GLITCHDET_CONFIG_ENABLE_Min 
#define GLITCHDET_GLITCHDETECTOR_CONFIG_ENABLE_Max GLITCHDET_CONFIG_ENABLE_Max
#define GLITCHDET_GLITCHDETECTOR_CONFIG_ENABLE_Disable GLITCHDET_CONFIG_ENABLE_Disable
#define GLITCHDET_GLITCHDETECTOR_CONFIG_ENABLE_Enable GLITCHDET_CONFIG_ENABLE_Enable


#define GLITCHDET_GLITCHDETECTOR_CONFIG_MODE_Pos  GLITCHDET_CONFIG_MODE_Pos                                        
#define GLITCHDET_GLITCHDETECTOR_CONFIG_MODE_Msk GLITCHDET_CONFIG_MODE_Msk                          
#define GLITCHDET_GLITCHDETECTOR_CONFIG_MODE_Min GLITCHDET_CONFIG_MODE_Min
#define GLITCHDET_GLITCHDETECTOR_CONFIG_MODE_Max GLITCHDET_CONFIG_MODE_Max
#define GLITCHDET_GLITCHDETECTOR_CONFIG_MODE_HighPassFilter GLITCHDET_CONFIG_MODE_HighPassFilter
#define GLITCHDET_GLITCHDETECTOR_CONFIG_MODE_CapDiv     GLITCHDET_CONFIG_MODE_CapDiv         

#define GLITCHDET_GLITCHDETECTOR_TRIM_ResetValue GLITCHDET_TRIM_ResetValue
#define GLITCHDET_GLITCHDETECTOR_TRIM_VREFLDVDD_Pos GLITCHDET_TRIM_VREFLDVDD_Pos
#define GLITCHDET_GLITCHDETECTOR_TRIM_VREFLDVDD_Msk GLITCHDET_TRIM_VREFLDVDD_Msk

#define GLITCHDET_GLITCHDETECTOR_TRIM_VREFLVDD_Pos GLITCHDET_TRIM_VREFLVDD_Pos
#define GLITCHDET_GLITCHDETECTOR_TRIM_VREFLVDD_Msk GLITCHDET_TRIM_VREFLVDD_Msk

#define GLITCHDET_GLITCHDETECTOR_TRIM_VREFHDVDD_Pos GLITCHDET_TRIM_VREFHDVDD_Pos
#define GLITCHDET_GLITCHDETECTOR_TRIM_VREFHDVDD_Msk GLITCHDET_TRIM_VREFHDVDD_Msk

#define GLITCHDET_GLITCHDETECTOR_TRIM_VREFHVDD_Pos  GLITCHDET_TRIM_VREFHVDD_Pos           
#define GLITCHDET_GLITCHDETECTOR_TRIM_VREFHVDD_Msk GLITCHDET_TRIM_VREFHVDD_Msk

#ifdef __cplusplus
}
#endif
#endif /* NRF54L15_ENGA_NAME_CHANGE_H */

