/*

Copyright (c) 2010 - 2022, Nordic Semiconductor ASA

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form, except as embedded into a Nordic
   Semiconductor ASA integrated circuit in a product or a software update for
   such product, must reproduce the above copyright notice, this list of
   conditions and the following disclaimer in the documentation and/or other
   materials provided with the distribution.

3. Neither the name of Nordic Semiconductor ASA nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

4. This software, with or without modification, must only be used with a
   Nordic Semiconductor ASA integrated circuit.

5. Any software provided in binary form under this license must not be reverse
   engineered, decompiled, modified and/or disassembled.

THIS SOFTWARE IS PROVIDED BY NORDIC SEMICONDUCTOR ASA "AS IS" AND ANY EXPRESS
OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY, NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL NORDIC SEMICONDUCTOR ASA OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#ifndef NRF9230_PPR_PERIPHERALS_H
#define NRF9230_PPR_PERIPHERALS_H

#ifdef __cplusplus
    extern "C" {
#endif

/*VPR CSR registers*/
#define VPRCSR_PRESENT
#define VPRCSR_COUNT 1

#define VPRCSR_HARTNUM 0
#define VPRCSR_MCLICBASERESET 4096
#define VPRCSR_MULDIV 2
#define VPRCSR_HIBERNATE 1
#define VPRCSR_DBG 1
#define VPRCSR_REMAP 0
#define VPRCSR_BUSWIDTH 64
#define VPRCSR_BKPT 2
#define VPRCSR_RT_VIO_PINS 0
#define VPRCSR_RT_SPLIT_SEC 0
#define VPRCSR_RT_SHIFT_PRESENT 0
#define VPRCSR_RT_SHIFT_START 0
#define VPRCSR_RT_SHIFT_LENGHT 32
#define VPRCSR_VEVIF_NTASKS 32
#define VPRCSR_VEVIF_NDPPI 32
#define VPRCSR_VEVIF_NEVENTS 32
#define VPRCSR_RST_UNRECOV 0
#define VPRCSR_BEXT 0

/*VPR CLIC registers*/
#define CLIC_PRESENT
#define CLIC_COUNT 1

#define VPRCLIC_MCLICBASE 4096
#define VPRCLIC_IRQNUM 480
#define VPRCLIC_CLIC_NTASKS 32
#define VPRCLIC_COUNTER_IRQ_NUM 32

/*VTIM CSR registers*/
#define VTIM_PRESENT
#define VTIM_COUNT 1

/*Factory Information Configuration Registers*/
#define FICR_PRESENT
#define FICR_COUNT 1

#define FICR_LTE_ON 1
#define FICR_NFC_ON 0

/*USBHSCORE*/
#define USBHSCORE_PRESENT
#define USBHSCORE_COUNT 1

/*I3CCORE*/
#define I3CCORE_PRESENT
#define I3CCORE_COUNT 2

/*System Trace Macrocell data buffer*/
#define STMDATA_PRESENT
#define STMDATA_COUNT 1

/*GENERIC*/
#define GENERIC_PRESENT
#define GENERIC_COUNT 3

/*System Trace Macrocell*/
#define STM_PRESENT
#define STM_COUNT 1

/*Trace Port Interface Unit*/
#define TPIU_PRESENT
#define TPIU_COUNT 1

/*Cross-Trigger Interface control*/
#define CTI_PRESENT
#define CTI_COUNT 2

/*ATB Replicator module*/
#define ATBREPLICATOR_PRESENT
#define ATBREPLICATOR_COUNT 4

/*ATB funnel module*/
#define ATBFUNNEL_PRESENT
#define ATBFUNNEL_COUNT 4

/*GPIO Tasks and Events*/
#define GPIOTE_PRESENT
#define GPIOTE_COUNT 2

/*Global Real-time counter*/
#define GRTC_PRESENT
#define GRTC_COUNT 1

#define GRTC_PWMREGS 1
#define GRTC_CLKOUTREG 1

/*TDDCONF*/
#define TDDCONF_PRESENT
#define TDDCONF_COUNT 1

/*Trace buffer monitor*/
#define TBM_PRESENT
#define TBM_COUNT 1

/*USBHS*/
#define USBHS_PRESENT
#define USBHS_COUNT 1

/*MRAM controller*/
#define MRAMC_PRESENT
#define MRAMC_COUNT 2

#define MRAMC110_NVRPAGEACC 1

#define MRAMC111_NVRPAGEACC 0

/*External Memory Interface*/
#define EXMIF_PRESENT
#define EXMIF_COUNT 1

/*AUXPLL*/
#define AUXPLL_PRESENT
#define AUXPLL_COUNT 1

/*AUXPM*/
#define AUXPM_PRESENT
#define AUXPM_COUNT 1

/*OTP controller*/
#define OTPC_PRESENT
#define OTPC_COUNT 1

#define OTPC_REGION_NO_EXTENSION 0
#define OTPC_REGION_EXTENSION 1
#define OTPC_NREGIONS 6
#define OTPC_REGION0ADDR 0
#define OTPC_REGION0SIZE 0
#define OTPC_REGION1ADDR 0
#define OTPC_REGION1SIZE 0
#define OTPC_REGION2ADDR 0
#define OTPC_REGION2SIZE 0
#define OTPC_REGION3ADDR 0
#define OTPC_REGION3SIZE 0
#define OTPC_REGION4ADDR 0
#define OTPC_REGION4SIZE 0
#define OTPC_REGION5ADDR 0
#define OTPC_REGION5SIZE 0

/*VPR peripheral registers*/
#define VPR_PRESENT
#define VPR_COUNT 3

#define VPR120_INIT_PC_RESET_VALUE 0
#define VPR120_VPR_START_RESET_VALUE 0
#define VPR120_RAM_BASE_ADDR 0
#define VPR120_RAM_SZ 0
#define VPR120_VPRSAVEDCTX 0
#define VPR120_VPRSAVEADDR 0
#define VPR120_VPRREMAPADDRVTOB 0
#define VPR120_VEVIF_NTASKS 32
#define VPR120_VEVIF_NDPPI 32
#define VPR120_VEVIF_NEVENTS 32

#define VPR121_INIT_PC_RESET_VALUE 0
#define VPR121_VPR_START_RESET_VALUE 0
#define VPR121_RAM_BASE_ADDR 0
#define VPR121_RAM_SZ 0
#define VPR121_VPRSAVEDCTX 0
#define VPR121_VPRSAVEADDR 0
#define VPR121_VPRREMAPADDRVTOB 0
#define VPR121_VEVIF_NTASKS 32
#define VPR121_VEVIF_NDPPI 32
#define VPR121_VEVIF_NEVENTS 32

#define VPR130_INIT_PC_RESET_VALUE 0
#define VPR130_VPR_START_RESET_VALUE 0
#define VPR130_RAM_BASE_ADDR 0
#define VPR130_RAM_SZ 0
#define VPR130_VPRSAVEDCTX 0
#define VPR130_VPRSAVEADDR 0
#define VPR130_VPRREMAPADDRVTOB 0
#define VPR130_VEVIF_NTASKS 32
#define VPR130_VEVIF_NDPPI 32
#define VPR130_VEVIF_NEVENTS 32

/*IPCT APB registers*/
#define IPCT_PRESENT
#define IPCT_COUNT 2

/*MUTEX*/
#define MUTEX_PRESENT
#define MUTEX_COUNT 2

/*I3C*/
#define I3C_PRESENT
#define I3C_COUNT 2

/*Controller Area Network*/
#define CAN_PRESENT
#define CAN_COUNT 1

/*MVDMA performs direct-memory-accesses between memories. Data is transferred according to job descriptor lists. Each transfer has corresponding source and sink descriptor lists with matching data amounts. The lists are in memory and they contain data buffer information, address pointers, buffer sizes and data type attributes.*/
                                                                                                                                  
#define MVDMA_PRESENT
#define MVDMA_COUNT 1

#define MVDMA120_COMPLETED_EVENT 1
#define MVDMA120_DPPI_DISCONNECTED 1

/*RAM Controller*/
#define RAMC_PRESENT
#define RAMC_COUNT 1

#define RAMC122_ECC 0
#define RAMC122_SEC 0

/*Distributed programmable peripheral interconnect controller*/
#define DPPIC_PRESENT
#define DPPIC_COUNT 8

#define DPPIC120_HASCHANNELGROUPS 1

#define DPPIC130_HASCHANNELGROUPS 1

#define DPPIC131_HASCHANNELGROUPS 1

#define DPPIC132_HASCHANNELGROUPS 1

#define DPPIC133_HASCHANNELGROUPS 1

#define DPPIC134_HASCHANNELGROUPS 1

#define DPPIC135_HASCHANNELGROUPS 1

#define DPPIC136_HASCHANNELGROUPS 1

/*Timer/Counter*/
#define TIMER_PRESENT
#define TIMER_COUNT 10

/*Pulse width modulation unit*/
#define PWM_PRESENT
#define PWM_COUNT 5

#define PWM120_EASYDMA5 0
#define PWM120_EASYDMATEMP 1
#define PWM120_IDLE_OUT 1
#define PWM120_COMPARE_MATCH 1
#define PWM120_EASYDMALISTINCLUDED 0
#define PWM120_EASYDMAMODEINCLUDED 0
#define PWM120_EASYDMAFULLLPMODEINCLUDED 0
#define PWM120_EASYDMAPATTERNMATCHERINCLUDED 0
#define PWM120_easyDMAMatchEventRange 4
#define PWM120_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED
#define PWM120_EASYDMASTOPTASKINCLUDED 1

#define PWM130_EASYDMA5 0
#define PWM130_EASYDMATEMP 1
#define PWM130_IDLE_OUT 1
#define PWM130_COMPARE_MATCH 1
#define PWM130_EASYDMALISTINCLUDED 0
#define PWM130_EASYDMAMODEINCLUDED 0
#define PWM130_EASYDMAFULLLPMODEINCLUDED 0
#define PWM130_EASYDMAPATTERNMATCHERINCLUDED 0
#define PWM130_easyDMAMatchEventRange 4
#define PWM130_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED
#define PWM130_EASYDMASTOPTASKINCLUDED 1

#define PWM131_EASYDMA5 0
#define PWM131_EASYDMATEMP 1
#define PWM131_IDLE_OUT 1
#define PWM131_COMPARE_MATCH 1
#define PWM131_EASYDMALISTINCLUDED 0
#define PWM131_EASYDMAMODEINCLUDED 0
#define PWM131_EASYDMAFULLLPMODEINCLUDED 0
#define PWM131_EASYDMAPATTERNMATCHERINCLUDED 0
#define PWM131_easyDMAMatchEventRange 4
#define PWM131_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED
#define PWM131_EASYDMASTOPTASKINCLUDED 1

#define PWM132_EASYDMA5 0
#define PWM132_EASYDMATEMP 1
#define PWM132_IDLE_OUT 1
#define PWM132_COMPARE_MATCH 1
#define PWM132_EASYDMALISTINCLUDED 0
#define PWM132_EASYDMAMODEINCLUDED 0
#define PWM132_EASYDMAFULLLPMODEINCLUDED 0
#define PWM132_EASYDMAPATTERNMATCHERINCLUDED 0
#define PWM132_easyDMAMatchEventRange 4
#define PWM132_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED
#define PWM132_EASYDMASTOPTASKINCLUDED 1

#define PWM133_EASYDMA5 0
#define PWM133_EASYDMATEMP 1
#define PWM133_IDLE_OUT 1
#define PWM133_COMPARE_MATCH 1
#define PWM133_EASYDMALISTINCLUDED 0
#define PWM133_EASYDMAMODEINCLUDED 0
#define PWM133_EASYDMAFULLLPMODEINCLUDED 0
#define PWM133_EASYDMAPATTERNMATCHERINCLUDED 0
#define PWM133_easyDMAMatchEventRange 4
#define PWM133_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED
#define PWM133_EASYDMASTOPTASKINCLUDED 1

/*SPI Slave*/
#define SPIS_PRESENT
#define SPIS_COUNT 9

#define SPIS120_LEGACYPSEL 0
#define SPIS120_LEGACYEDMA 0
#define SPIS120_EASYDMA_MAXCNT_SIZE 16
#define SPIS120_EASYDMA5 0
#define SPIS120_EASYDMATEMP 1
#define SPIS120_EASYDMALISTINCLUDED 0
#define SPIS120_EASYDMAMODEINCLUDED 0
#define SPIS120_EASYDMAFULLLPMODEINCLUDED 0
#define SPIS120_EASYDMAPATTERNMATCHERINCLUDED 0

#define SPIS130_LEGACYPSEL 0
#define SPIS130_LEGACYEDMA 0
#define SPIS130_EASYDMA_MAXCNT_SIZE 16
#define SPIS130_EASYDMA5 0
#define SPIS130_EASYDMATEMP 1
#define SPIS130_EASYDMALISTINCLUDED 0
#define SPIS130_EASYDMAMODEINCLUDED 0
#define SPIS130_EASYDMAFULLLPMODEINCLUDED 0
#define SPIS130_EASYDMAPATTERNMATCHERINCLUDED 0

#define SPIS131_LEGACYPSEL 0
#define SPIS131_LEGACYEDMA 0
#define SPIS131_EASYDMA_MAXCNT_SIZE 16
#define SPIS131_EASYDMA5 0
#define SPIS131_EASYDMATEMP 1
#define SPIS131_EASYDMALISTINCLUDED 0
#define SPIS131_EASYDMAMODEINCLUDED 0
#define SPIS131_EASYDMAFULLLPMODEINCLUDED 0
#define SPIS131_EASYDMAPATTERNMATCHERINCLUDED 0

#define SPIS132_LEGACYPSEL 0
#define SPIS132_LEGACYEDMA 0
#define SPIS132_EASYDMA_MAXCNT_SIZE 16
#define SPIS132_EASYDMA5 0
#define SPIS132_EASYDMATEMP 1
#define SPIS132_EASYDMALISTINCLUDED 0
#define SPIS132_EASYDMAMODEINCLUDED 0
#define SPIS132_EASYDMAFULLLPMODEINCLUDED 0
#define SPIS132_EASYDMAPATTERNMATCHERINCLUDED 0

#define SPIS133_LEGACYPSEL 0
#define SPIS133_LEGACYEDMA 0
#define SPIS133_EASYDMA_MAXCNT_SIZE 16
#define SPIS133_EASYDMA5 0
#define SPIS133_EASYDMATEMP 1
#define SPIS133_EASYDMALISTINCLUDED 0
#define SPIS133_EASYDMAMODEINCLUDED 0
#define SPIS133_EASYDMAFULLLPMODEINCLUDED 0
#define SPIS133_EASYDMAPATTERNMATCHERINCLUDED 0

#define SPIS134_LEGACYPSEL 0
#define SPIS134_LEGACYEDMA 0
#define SPIS134_EASYDMA_MAXCNT_SIZE 16
#define SPIS134_EASYDMA5 0
#define SPIS134_EASYDMATEMP 1
#define SPIS134_EASYDMALISTINCLUDED 0
#define SPIS134_EASYDMAMODEINCLUDED 0
#define SPIS134_EASYDMAFULLLPMODEINCLUDED 0
#define SPIS134_EASYDMAPATTERNMATCHERINCLUDED 0

#define SPIS135_LEGACYPSEL 0
#define SPIS135_LEGACYEDMA 0
#define SPIS135_EASYDMA_MAXCNT_SIZE 16
#define SPIS135_EASYDMA5 0
#define SPIS135_EASYDMATEMP 1
#define SPIS135_EASYDMALISTINCLUDED 0
#define SPIS135_EASYDMAMODEINCLUDED 0
#define SPIS135_EASYDMAFULLLPMODEINCLUDED 0
#define SPIS135_EASYDMAPATTERNMATCHERINCLUDED 0

#define SPIS136_LEGACYPSEL 0
#define SPIS136_LEGACYEDMA 0
#define SPIS136_EASYDMA_MAXCNT_SIZE 16
#define SPIS136_EASYDMA5 0
#define SPIS136_EASYDMATEMP 1
#define SPIS136_EASYDMALISTINCLUDED 0
#define SPIS136_EASYDMAMODEINCLUDED 0
#define SPIS136_EASYDMAFULLLPMODEINCLUDED 0
#define SPIS136_EASYDMAPATTERNMATCHERINCLUDED 0

#define SPIS137_LEGACYPSEL 0
#define SPIS137_LEGACYEDMA 0
#define SPIS137_EASYDMA_MAXCNT_SIZE 16
#define SPIS137_EASYDMA5 0
#define SPIS137_EASYDMATEMP 1
#define SPIS137_EASYDMALISTINCLUDED 0
#define SPIS137_EASYDMAMODEINCLUDED 0
#define SPIS137_EASYDMAFULLLPMODEINCLUDED 0
#define SPIS137_EASYDMAPATTERNMATCHERINCLUDED 0

/*UART with EasyDMA*/
#define UARTE_PRESENT
#define UARTE_COUNT 9

#define UARTE120_EASYDMA_MAXCNT_SIZE 8
#define UARTE120_EASYDMA5 0
#define UARTE120_EASYDMATEMP 1
#define UARTE120_TIMEOUT_INTERRUPT 0
#define UARTE120_CONFIGURABLE_DATA_FRAME_SIZE 0
#define UARTE120_CORE_CLOCK_16 0
#define UARTE120_CORE_CLOCK_320 1
#define UARTE120_EASYDMALISTINCLUDED 0
#define UARTE120_EASYDMAMODEINCLUDED 0
#define UARTE120_EASYDMAFULLLPMODEINCLUDED 0
#define UARTE120_EASYDMAPATTERNMATCHERINCLUDED 0
#define UARTE120_easyDMAMatchEventRange 4
#define UARTE120_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define UARTE120_EASYDMASTOPTASKINCLUDED 1

#define UARTE130_EASYDMA_MAXCNT_SIZE 8
#define UARTE130_EASYDMA5 0
#define UARTE130_EASYDMATEMP 1
#define UARTE130_TIMEOUT_INTERRUPT 0
#define UARTE130_CONFIGURABLE_DATA_FRAME_SIZE 0
#define UARTE130_CORE_CLOCK_16 1
#define UARTE130_CORE_CLOCK_320 0
#define UARTE130_EASYDMALISTINCLUDED 0
#define UARTE130_EASYDMAMODEINCLUDED 0
#define UARTE130_EASYDMAFULLLPMODEINCLUDED 0
#define UARTE130_EASYDMAPATTERNMATCHERINCLUDED 0
#define UARTE130_easyDMAMatchEventRange 4
#define UARTE130_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define UARTE130_EASYDMASTOPTASKINCLUDED 1

#define UARTE131_EASYDMA_MAXCNT_SIZE 8
#define UARTE131_EASYDMA5 0
#define UARTE131_EASYDMATEMP 1
#define UARTE131_TIMEOUT_INTERRUPT 0
#define UARTE131_CONFIGURABLE_DATA_FRAME_SIZE 0
#define UARTE131_CORE_CLOCK_16 1
#define UARTE131_CORE_CLOCK_320 0
#define UARTE131_EASYDMALISTINCLUDED 0
#define UARTE131_EASYDMAMODEINCLUDED 0
#define UARTE131_EASYDMAFULLLPMODEINCLUDED 0
#define UARTE131_EASYDMAPATTERNMATCHERINCLUDED 0
#define UARTE131_easyDMAMatchEventRange 4
#define UARTE131_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define UARTE131_EASYDMASTOPTASKINCLUDED 1

#define UARTE132_EASYDMA_MAXCNT_SIZE 8
#define UARTE132_EASYDMA5 0
#define UARTE132_EASYDMATEMP 1
#define UARTE132_TIMEOUT_INTERRUPT 0
#define UARTE132_CONFIGURABLE_DATA_FRAME_SIZE 0
#define UARTE132_CORE_CLOCK_16 1
#define UARTE132_CORE_CLOCK_320 0
#define UARTE132_EASYDMALISTINCLUDED 0
#define UARTE132_EASYDMAMODEINCLUDED 0
#define UARTE132_EASYDMAFULLLPMODEINCLUDED 0
#define UARTE132_EASYDMAPATTERNMATCHERINCLUDED 0
#define UARTE132_easyDMAMatchEventRange 4
#define UARTE132_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define UARTE132_EASYDMASTOPTASKINCLUDED 1

#define UARTE133_EASYDMA_MAXCNT_SIZE 8
#define UARTE133_EASYDMA5 0
#define UARTE133_EASYDMATEMP 1
#define UARTE133_TIMEOUT_INTERRUPT 0
#define UARTE133_CONFIGURABLE_DATA_FRAME_SIZE 0
#define UARTE133_CORE_CLOCK_16 1
#define UARTE133_CORE_CLOCK_320 0
#define UARTE133_EASYDMALISTINCLUDED 0
#define UARTE133_EASYDMAMODEINCLUDED 0
#define UARTE133_EASYDMAFULLLPMODEINCLUDED 0
#define UARTE133_EASYDMAPATTERNMATCHERINCLUDED 0
#define UARTE133_easyDMAMatchEventRange 4
#define UARTE133_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define UARTE133_EASYDMASTOPTASKINCLUDED 1

#define UARTE134_EASYDMA_MAXCNT_SIZE 8
#define UARTE134_EASYDMA5 0
#define UARTE134_EASYDMATEMP 1
#define UARTE134_TIMEOUT_INTERRUPT 0
#define UARTE134_CONFIGURABLE_DATA_FRAME_SIZE 0
#define UARTE134_CORE_CLOCK_16 1
#define UARTE134_CORE_CLOCK_320 0
#define UARTE134_EASYDMALISTINCLUDED 0
#define UARTE134_EASYDMAMODEINCLUDED 0
#define UARTE134_EASYDMAFULLLPMODEINCLUDED 0
#define UARTE134_EASYDMAPATTERNMATCHERINCLUDED 0
#define UARTE134_easyDMAMatchEventRange 4
#define UARTE134_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define UARTE134_EASYDMASTOPTASKINCLUDED 1

#define UARTE135_EASYDMA_MAXCNT_SIZE 8
#define UARTE135_EASYDMA5 0
#define UARTE135_EASYDMATEMP 1
#define UARTE135_TIMEOUT_INTERRUPT 0
#define UARTE135_CONFIGURABLE_DATA_FRAME_SIZE 0
#define UARTE135_CORE_CLOCK_16 1
#define UARTE135_CORE_CLOCK_320 0
#define UARTE135_EASYDMALISTINCLUDED 0
#define UARTE135_EASYDMAMODEINCLUDED 0
#define UARTE135_EASYDMAFULLLPMODEINCLUDED 0
#define UARTE135_EASYDMAPATTERNMATCHERINCLUDED 0
#define UARTE135_easyDMAMatchEventRange 4
#define UARTE135_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define UARTE135_EASYDMASTOPTASKINCLUDED 1

#define UARTE136_EASYDMA_MAXCNT_SIZE 8
#define UARTE136_EASYDMA5 0
#define UARTE136_EASYDMATEMP 1
#define UARTE136_TIMEOUT_INTERRUPT 0
#define UARTE136_CONFIGURABLE_DATA_FRAME_SIZE 0
#define UARTE136_CORE_CLOCK_16 1
#define UARTE136_CORE_CLOCK_320 0
#define UARTE136_EASYDMALISTINCLUDED 0
#define UARTE136_EASYDMAMODEINCLUDED 0
#define UARTE136_EASYDMAFULLLPMODEINCLUDED 0
#define UARTE136_EASYDMAPATTERNMATCHERINCLUDED 0
#define UARTE136_easyDMAMatchEventRange 4
#define UARTE136_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define UARTE136_EASYDMASTOPTASKINCLUDED 1

#define UARTE137_EASYDMA_MAXCNT_SIZE 8
#define UARTE137_EASYDMA5 0
#define UARTE137_EASYDMATEMP 1
#define UARTE137_TIMEOUT_INTERRUPT 0
#define UARTE137_CONFIGURABLE_DATA_FRAME_SIZE 0
#define UARTE137_CORE_CLOCK_16 1
#define UARTE137_CORE_CLOCK_320 0
#define UARTE137_EASYDMALISTINCLUDED 0
#define UARTE137_EASYDMAMODEINCLUDED 0
#define UARTE137_EASYDMAFULLLPMODEINCLUDED 0
#define UARTE137_EASYDMAPATTERNMATCHERINCLUDED 0
#define UARTE137_easyDMAMatchEventRange 4
#define UARTE137_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED 0
#define UARTE137_EASYDMASTOPTASKINCLUDED 1

/*Serial Peripheral Interface Master with EasyDMA*/
#define SPIM_PRESENT
#define SPIM_COUNT 10

#define SPIM120_EASYDMA5 0
#define SPIM120_EASYDMATEMP 1
#define SPIM120_EASYDMALISTINCLUDED 0
#define SPIM120_EASYDMAMODEINCLUDED 0
#define SPIM120_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM120_EASYDMAPATTERNMATCHERINCLUDED 0
#define SPIM120_MAX_DATARATE 8
#define SPIM120_EASYDMA_MAXCNT_SIZE 16
#define SPIM120_FEATURE_HARDWARE_CSN_PRESENT 0
#define SPIM120_FEATURE_HARDWARE_DCX_PRESENT 0
#define SPIM120_FEATURE_RXDELAY_PRESENT 0
#define SPIM120_STALL_STATUS_PRESENT 0
#define SPIM120_STALL_STATUS_TX_PRESENT 0
#define SPIM120_HSSPI 0
#define SPIM120_HIGH_SPEED_DOMAIN 0
#define SPIM120_MULTIPLE_CHIPSELECT 0
#define SPIM120_NUM_CHIPSELECT 1
#define SPIM120_CORE_FREQUENCY 32
#define SPIM120_PRESCALER_PRESENT 125
#define SPIM120_PRESCALER_DIVISOR_RANGE 125

#define SPIM121_EASYDMA5 0
#define SPIM121_EASYDMATEMP 1
#define SPIM121_EASYDMALISTINCLUDED 0
#define SPIM121_EASYDMAMODEINCLUDED 0
#define SPIM121_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM121_EASYDMAPATTERNMATCHERINCLUDED 0
#define SPIM121_MAX_DATARATE 8
#define SPIM121_EASYDMA_MAXCNT_SIZE 16
#define SPIM121_FEATURE_HARDWARE_CSN_PRESENT 0
#define SPIM121_FEATURE_HARDWARE_DCX_PRESENT 0
#define SPIM121_FEATURE_RXDELAY_PRESENT 0
#define SPIM121_STALL_STATUS_PRESENT 0
#define SPIM121_STALL_STATUS_TX_PRESENT 0
#define SPIM121_HSSPI 0
#define SPIM121_HIGH_SPEED_DOMAIN 0
#define SPIM121_MULTIPLE_CHIPSELECT 0
#define SPIM121_NUM_CHIPSELECT 1
#define SPIM121_CORE_FREQUENCY 32
#define SPIM121_PRESCALER_PRESENT 125
#define SPIM121_PRESCALER_DIVISOR_RANGE 125

#define SPIM130_EASYDMA5 0
#define SPIM130_EASYDMATEMP 1
#define SPIM130_EASYDMALISTINCLUDED 0
#define SPIM130_EASYDMAMODEINCLUDED 0
#define SPIM130_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM130_EASYDMAPATTERNMATCHERINCLUDED 0
#define SPIM130_MAX_DATARATE 8
#define SPIM130_EASYDMA_MAXCNT_SIZE 16
#define SPIM130_FEATURE_HARDWARE_CSN_PRESENT 0
#define SPIM130_FEATURE_HARDWARE_DCX_PRESENT 0
#define SPIM130_FEATURE_RXDELAY_PRESENT 0
#define SPIM130_STALL_STATUS_PRESENT 0
#define SPIM130_STALL_STATUS_TX_PRESENT 0
#define SPIM130_HSSPI 0
#define SPIM130_HIGH_SPEED_DOMAIN 0
#define SPIM130_MULTIPLE_CHIPSELECT 0
#define SPIM130_NUM_CHIPSELECT 1
#define SPIM130_CORE_FREQUENCY 32
#define SPIM130_PRESCALER_PRESENT 125
#define SPIM130_PRESCALER_DIVISOR_RANGE 125

#define SPIM131_EASYDMA5 0
#define SPIM131_EASYDMATEMP 1
#define SPIM131_EASYDMALISTINCLUDED 0
#define SPIM131_EASYDMAMODEINCLUDED 0
#define SPIM131_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM131_EASYDMAPATTERNMATCHERINCLUDED 0
#define SPIM131_MAX_DATARATE 8
#define SPIM131_EASYDMA_MAXCNT_SIZE 16
#define SPIM131_FEATURE_HARDWARE_CSN_PRESENT 0
#define SPIM131_FEATURE_HARDWARE_DCX_PRESENT 0
#define SPIM131_FEATURE_RXDELAY_PRESENT 0
#define SPIM131_STALL_STATUS_PRESENT 0
#define SPIM131_STALL_STATUS_TX_PRESENT 0
#define SPIM131_HSSPI 0
#define SPIM131_HIGH_SPEED_DOMAIN 0
#define SPIM131_MULTIPLE_CHIPSELECT 0
#define SPIM131_NUM_CHIPSELECT 1
#define SPIM131_CORE_FREQUENCY 32
#define SPIM131_PRESCALER_PRESENT 125
#define SPIM131_PRESCALER_DIVISOR_RANGE 125

#define SPIM132_EASYDMA5 0
#define SPIM132_EASYDMATEMP 1
#define SPIM132_EASYDMALISTINCLUDED 0
#define SPIM132_EASYDMAMODEINCLUDED 0
#define SPIM132_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM132_EASYDMAPATTERNMATCHERINCLUDED 0
#define SPIM132_MAX_DATARATE 8
#define SPIM132_EASYDMA_MAXCNT_SIZE 16
#define SPIM132_FEATURE_HARDWARE_CSN_PRESENT 0
#define SPIM132_FEATURE_HARDWARE_DCX_PRESENT 0
#define SPIM132_FEATURE_RXDELAY_PRESENT 0
#define SPIM132_STALL_STATUS_PRESENT 0
#define SPIM132_STALL_STATUS_TX_PRESENT 0
#define SPIM132_HSSPI 0
#define SPIM132_HIGH_SPEED_DOMAIN 0
#define SPIM132_MULTIPLE_CHIPSELECT 0
#define SPIM132_NUM_CHIPSELECT 1
#define SPIM132_CORE_FREQUENCY 32
#define SPIM132_PRESCALER_PRESENT 125
#define SPIM132_PRESCALER_DIVISOR_RANGE 125

#define SPIM133_EASYDMA5 0
#define SPIM133_EASYDMATEMP 1
#define SPIM133_EASYDMALISTINCLUDED 0
#define SPIM133_EASYDMAMODEINCLUDED 0
#define SPIM133_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM133_EASYDMAPATTERNMATCHERINCLUDED 0
#define SPIM133_MAX_DATARATE 8
#define SPIM133_EASYDMA_MAXCNT_SIZE 16
#define SPIM133_FEATURE_HARDWARE_CSN_PRESENT 0
#define SPIM133_FEATURE_HARDWARE_DCX_PRESENT 0
#define SPIM133_FEATURE_RXDELAY_PRESENT 0
#define SPIM133_STALL_STATUS_PRESENT 0
#define SPIM133_STALL_STATUS_TX_PRESENT 0
#define SPIM133_HSSPI 0
#define SPIM133_HIGH_SPEED_DOMAIN 0
#define SPIM133_MULTIPLE_CHIPSELECT 0
#define SPIM133_NUM_CHIPSELECT 1
#define SPIM133_CORE_FREQUENCY 32
#define SPIM133_PRESCALER_PRESENT 125
#define SPIM133_PRESCALER_DIVISOR_RANGE 125

#define SPIM134_EASYDMA5 0
#define SPIM134_EASYDMATEMP 1
#define SPIM134_EASYDMALISTINCLUDED 0
#define SPIM134_EASYDMAMODEINCLUDED 0
#define SPIM134_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM134_EASYDMAPATTERNMATCHERINCLUDED 0
#define SPIM134_MAX_DATARATE 8
#define SPIM134_EASYDMA_MAXCNT_SIZE 16
#define SPIM134_FEATURE_HARDWARE_CSN_PRESENT 0
#define SPIM134_FEATURE_HARDWARE_DCX_PRESENT 0
#define SPIM134_FEATURE_RXDELAY_PRESENT 0
#define SPIM134_STALL_STATUS_PRESENT 0
#define SPIM134_STALL_STATUS_TX_PRESENT 0
#define SPIM134_HSSPI 0
#define SPIM134_HIGH_SPEED_DOMAIN 0
#define SPIM134_MULTIPLE_CHIPSELECT 0
#define SPIM134_NUM_CHIPSELECT 1
#define SPIM134_CORE_FREQUENCY 32
#define SPIM134_PRESCALER_PRESENT 125
#define SPIM134_PRESCALER_DIVISOR_RANGE 125

#define SPIM135_EASYDMA5 0
#define SPIM135_EASYDMATEMP 1
#define SPIM135_EASYDMALISTINCLUDED 0
#define SPIM135_EASYDMAMODEINCLUDED 0
#define SPIM135_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM135_EASYDMAPATTERNMATCHERINCLUDED 0
#define SPIM135_MAX_DATARATE 8
#define SPIM135_EASYDMA_MAXCNT_SIZE 16
#define SPIM135_FEATURE_HARDWARE_CSN_PRESENT 0
#define SPIM135_FEATURE_HARDWARE_DCX_PRESENT 0
#define SPIM135_FEATURE_RXDELAY_PRESENT 0
#define SPIM135_STALL_STATUS_PRESENT 0
#define SPIM135_STALL_STATUS_TX_PRESENT 0
#define SPIM135_HSSPI 0
#define SPIM135_HIGH_SPEED_DOMAIN 0
#define SPIM135_MULTIPLE_CHIPSELECT 0
#define SPIM135_NUM_CHIPSELECT 1
#define SPIM135_CORE_FREQUENCY 32
#define SPIM135_PRESCALER_PRESENT 125
#define SPIM135_PRESCALER_DIVISOR_RANGE 125

#define SPIM136_EASYDMA5 0
#define SPIM136_EASYDMATEMP 1
#define SPIM136_EASYDMALISTINCLUDED 0
#define SPIM136_EASYDMAMODEINCLUDED 0
#define SPIM136_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM136_EASYDMAPATTERNMATCHERINCLUDED 0
#define SPIM136_MAX_DATARATE 8
#define SPIM136_EASYDMA_MAXCNT_SIZE 16
#define SPIM136_FEATURE_HARDWARE_CSN_PRESENT 0
#define SPIM136_FEATURE_HARDWARE_DCX_PRESENT 0
#define SPIM136_FEATURE_RXDELAY_PRESENT 0
#define SPIM136_STALL_STATUS_PRESENT 0
#define SPIM136_STALL_STATUS_TX_PRESENT 0
#define SPIM136_HSSPI 0
#define SPIM136_HIGH_SPEED_DOMAIN 0
#define SPIM136_MULTIPLE_CHIPSELECT 0
#define SPIM136_NUM_CHIPSELECT 1
#define SPIM136_CORE_FREQUENCY 32
#define SPIM136_PRESCALER_PRESENT 125
#define SPIM136_PRESCALER_DIVISOR_RANGE 125

#define SPIM137_EASYDMA5 0
#define SPIM137_EASYDMATEMP 1
#define SPIM137_EASYDMALISTINCLUDED 0
#define SPIM137_EASYDMAMODEINCLUDED 0
#define SPIM137_EASYDMAFULLLPMODEINCLUDED 0
#define SPIM137_EASYDMAPATTERNMATCHERINCLUDED 0
#define SPIM137_MAX_DATARATE 8
#define SPIM137_EASYDMA_MAXCNT_SIZE 16
#define SPIM137_FEATURE_HARDWARE_CSN_PRESENT 0
#define SPIM137_FEATURE_HARDWARE_DCX_PRESENT 0
#define SPIM137_FEATURE_RXDELAY_PRESENT 0
#define SPIM137_STALL_STATUS_PRESENT 0
#define SPIM137_STALL_STATUS_TX_PRESENT 0
#define SPIM137_HSSPI 0
#define SPIM137_HIGH_SPEED_DOMAIN 0
#define SPIM137_MULTIPLE_CHIPSELECT 0
#define SPIM137_NUM_CHIPSELECT 1
#define SPIM137_CORE_FREQUENCY 32
#define SPIM137_PRESCALER_PRESENT 125
#define SPIM137_PRESCALER_DIVISOR_RANGE 125

/*I2C compatible Two-Wire Master Interface with EasyDMA*/
#define TWIM_PRESENT
#define TWIM_COUNT 9

#define TWIM120_EASYDMA5 0
#define TWIM120_EASYDMATEMP 1
#define TWIM120_EASYDMALISTINCLUDED 0
#define TWIM120_EASYDMAMODEINCLUDED 0
#define TWIM120_EASYDMAFULLLPMODEINCLUDED 0
#define TWIM120_EASYDMAPATTERNMATCHERINCLUDED 0
#define TWIM120_easyDMAMatchEventRange 4

#define TWIM130_EASYDMA5 0
#define TWIM130_EASYDMATEMP 1
#define TWIM130_EASYDMALISTINCLUDED 0
#define TWIM130_EASYDMAMODEINCLUDED 0
#define TWIM130_EASYDMAFULLLPMODEINCLUDED 0
#define TWIM130_EASYDMAPATTERNMATCHERINCLUDED 0
#define TWIM130_easyDMAMatchEventRange 4

#define TWIM131_EASYDMA5 0
#define TWIM131_EASYDMATEMP 1
#define TWIM131_EASYDMALISTINCLUDED 0
#define TWIM131_EASYDMAMODEINCLUDED 0
#define TWIM131_EASYDMAFULLLPMODEINCLUDED 0
#define TWIM131_EASYDMAPATTERNMATCHERINCLUDED 0
#define TWIM131_easyDMAMatchEventRange 4

#define TWIM132_EASYDMA5 0
#define TWIM132_EASYDMATEMP 1
#define TWIM132_EASYDMALISTINCLUDED 0
#define TWIM132_EASYDMAMODEINCLUDED 0
#define TWIM132_EASYDMAFULLLPMODEINCLUDED 0
#define TWIM132_EASYDMAPATTERNMATCHERINCLUDED 0
#define TWIM132_easyDMAMatchEventRange 4

#define TWIM133_EASYDMA5 0
#define TWIM133_EASYDMATEMP 1
#define TWIM133_EASYDMALISTINCLUDED 0
#define TWIM133_EASYDMAMODEINCLUDED 0
#define TWIM133_EASYDMAFULLLPMODEINCLUDED 0
#define TWIM133_EASYDMAPATTERNMATCHERINCLUDED 0
#define TWIM133_easyDMAMatchEventRange 4

#define TWIM134_EASYDMA5 0
#define TWIM134_EASYDMATEMP 1
#define TWIM134_EASYDMALISTINCLUDED 0
#define TWIM134_EASYDMAMODEINCLUDED 0
#define TWIM134_EASYDMAFULLLPMODEINCLUDED 0
#define TWIM134_EASYDMAPATTERNMATCHERINCLUDED 0
#define TWIM134_easyDMAMatchEventRange 4

#define TWIM135_EASYDMA5 0
#define TWIM135_EASYDMATEMP 1
#define TWIM135_EASYDMALISTINCLUDED 0
#define TWIM135_EASYDMAMODEINCLUDED 0
#define TWIM135_EASYDMAFULLLPMODEINCLUDED 0
#define TWIM135_EASYDMAPATTERNMATCHERINCLUDED 0
#define TWIM135_easyDMAMatchEventRange 4

#define TWIM136_EASYDMA5 0
#define TWIM136_EASYDMATEMP 1
#define TWIM136_EASYDMALISTINCLUDED 0
#define TWIM136_EASYDMAMODEINCLUDED 0
#define TWIM136_EASYDMAFULLLPMODEINCLUDED 0
#define TWIM136_EASYDMAPATTERNMATCHERINCLUDED 0
#define TWIM136_easyDMAMatchEventRange 4

#define TWIM137_EASYDMA5 0
#define TWIM137_EASYDMATEMP 1
#define TWIM137_EASYDMALISTINCLUDED 0
#define TWIM137_EASYDMAMODEINCLUDED 0
#define TWIM137_EASYDMAFULLLPMODEINCLUDED 0
#define TWIM137_EASYDMAPATTERNMATCHERINCLUDED 0
#define TWIM137_easyDMAMatchEventRange 4

/*Sample accumulator router*/
#define SACR_PRESENT
#define SACR_COUNT 1

/*Real-time counter*/
#define RTC_PRESENT
#define RTC_COUNT 2

/*Watchdog Timer*/
#define WDT_PRESENT
#define WDT_COUNT 2

#define WDT131_START_ON_RESET 0
#define WDT131_CRV_RESETVALUE 4294967295
#define WDT131_ALLOW_STOP 0

#define WDT132_START_ON_RESET 0
#define WDT132_CRV_RESETVALUE 4294967295
#define WDT132_ALLOW_STOP 0

/*Event generator unit*/
#define EGU_PRESENT
#define EGU_COUNT 1

#define EGU130_PEND 0
#define EGU130_CH_NUM 8

/*GPIO Port*/
#define GPIO_PRESENT
#define GPIO_COUNT 16

#define P0_PIN_NUM 32
#define P0_PINS_PRESENT 0xFFFFFFFFUL
#define P0_DRIVECTRL 0
#define P0_PWRCTRL 0
#define P0_pwrctrl_separate_reg 0
#define P0_PIN_OWNER_SEC 1

#define P1_PIN_NUM 32
#define P1_PINS_PRESENT 0xFFFFFFFFUL
#define P1_DRIVECTRL 0
#define P1_PWRCTRL 0
#define P1_pwrctrl_separate_reg 0
#define P1_PIN_OWNER_SEC 1

#define P2_PIN_NUM 32
#define P2_PINS_PRESENT 0xFFFFFFFFUL
#define P2_DRIVECTRL 0
#define P2_PWRCTRL 0
#define P2_pwrctrl_separate_reg 0
#define P2_PIN_OWNER_SEC 1

#define P3_PIN_NUM 32
#define P3_PINS_PRESENT 0xFFFFFFFFUL
#define P3_DRIVECTRL 0
#define P3_PWRCTRL 0
#define P3_pwrctrl_separate_reg 0
#define P3_PIN_OWNER_SEC 1

#define P4_PIN_NUM 32
#define P4_PINS_PRESENT 0xFFFFFFFFUL
#define P4_DRIVECTRL 0
#define P4_PWRCTRL 0
#define P4_pwrctrl_separate_reg 0
#define P4_PIN_OWNER_SEC 1

#define P5_PIN_NUM 32
#define P5_PINS_PRESENT 0xFFFFFFFFUL
#define P5_DRIVECTRL 0
#define P5_PWRCTRL 0
#define P5_pwrctrl_separate_reg 0
#define P5_PIN_OWNER_SEC 1

#define P6_PIN_NUM 32
#define P6_PINS_PRESENT 0xFFFFFFFFUL
#define P6_DRIVECTRL 1
#define P6_PWRCTRL 0
#define P6_pwrctrl_separate_reg 0
#define P6_PIN_OWNER_SEC 1

#define P7_PIN_NUM 32
#define P7_PINS_PRESENT 0xFFFFFFFFUL
#define P7_DRIVECTRL 1
#define P7_PWRCTRL 0
#define P7_pwrctrl_separate_reg 0
#define P7_PIN_OWNER_SEC 1

#define P8_PIN_NUM 32
#define P8_PINS_PRESENT 0xFFFFFFFFUL
#define P8_DRIVECTRL 1
#define P8_PWRCTRL 0
#define P8_pwrctrl_separate_reg 0
#define P8_PIN_OWNER_SEC 1

#define P9_PIN_NUM 32
#define P9_PINS_PRESENT 0xFFFFFFFFUL
#define P9_DRIVECTRL 0
#define P9_PWRCTRL 1
#define P9_pwrctrl_separate_reg 0
#define P9_PIN_OWNER_SEC 1

#define P10_PIN_NUM 32
#define P10_PINS_PRESENT 0xFFFFFFFFUL
#define P10_DRIVECTRL 0
#define P10_PWRCTRL 0
#define P10_pwrctrl_separate_reg 0
#define P10_PIN_OWNER_SEC 1

#define P11_PIN_NUM 32
#define P11_PINS_PRESENT 0xFFFFFFFFUL
#define P11_DRIVECTRL 0
#define P11_PWRCTRL 0
#define P11_pwrctrl_separate_reg 0
#define P11_PIN_OWNER_SEC 1

#define P12_PIN_NUM 32
#define P12_PINS_PRESENT 0xFFFFFFFFUL
#define P12_DRIVECTRL 0
#define P12_PWRCTRL 0
#define P12_pwrctrl_separate_reg 0
#define P12_PIN_OWNER_SEC 1

#define P13_PIN_NUM 32
#define P13_PINS_PRESENT 0xFFFFFFFFUL
#define P13_DRIVECTRL 0
#define P13_PWRCTRL 0
#define P13_pwrctrl_separate_reg 0
#define P13_PIN_OWNER_SEC 1

#define P14_PIN_NUM 32
#define P14_PINS_PRESENT 0xFFFFFFFFUL
#define P14_DRIVECTRL 0
#define P14_PWRCTRL 0
#define P14_pwrctrl_separate_reg 0
#define P14_PIN_OWNER_SEC 1

#define P15_PIN_NUM 32
#define P15_PINS_PRESENT 0xFFFFFFFFUL
#define P15_DRIVECTRL 0
#define P15_PWRCTRL 0
#define P15_pwrctrl_separate_reg 0
#define P15_PIN_OWNER_SEC 1

/*GPIO Internal*/
#define GPIOINTERNAL_PRESENT
#define GPIOINTERNAL_COUNT 1

/*Reset hub*/
#define RESETHUB_PRESENT
#define RESETHUB_COUNT 1

/*Analog to Digital Converter*/
#define SAADC_PRESENT
#define SAADC_COUNT 1

#define SAADC_EASYDMA5 0
#define SAADC_EASYDMATEMP 1
#define SAADC_EASYDMALISTINCLUDED 0
#define SAADC_EASYDMAMODEINCLUDED 0
#define SAADC_EASYDMAFULLLPMODEINCLUDED 0
#define SAADC_EASYDMAPATTERNMATCHERINCLUDED 0
#define SAADC_easyDMAMatchEventRange 4
#define SAADC_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED

/*Comparator*/
#define COMP_PRESENT
#define COMP_COUNT 1

/*Low-power comparator*/
#define LPCOMP_PRESENT
#define LPCOMP_COUNT 1

/*Temperature Sensor*/
#define TEMP_PRESENT
#define TEMP_COUNT 1

/*Inter-IC Sound*/
#define I2S_PRESENT
#define I2S_COUNT 2

/*Pulse Density Modulation (Digital Microphone) Interface*/
#define PDM_PRESENT
#define PDM_COUNT 1

#define PDM_EASYDMA5 0
#define PDM_EASYDMATEMP 1
#define PDM_EASYDMALISTINCLUDED 0
#define PDM_EASYDMAMODEINCLUDED 0
#define PDM_EASYDMAFULLLPMODEINCLUDED 0
#define PDM_EASYDMAPATTERNMATCHERINCLUDED 0
#define PDM_easyDMAMatchEventRange 4
#define PDM_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED

/*Quadrature Decoder*/
#define QDEC_PRESENT
#define QDEC_COUNT 2

#define QDEC130_LEGACYPSEL 0

#define QDEC131_LEGACYPSEL 0

/*SIM card interface*/
#define SIMIF_PRESENT
#define SIMIF_COUNT 2

/*MipiRffe Master*/
#define MIPIRFFE_PRESENT
#define MIPIRFFE_COUNT 1

/*I2C compatible Two-Wire Slave Interface with EasyDMA*/
#define TWIS_PRESENT
#define TWIS_COUNT 8

#define TWIS130_EASYDMA5 0
#define TWIS130_EASYDMATEMP 1
#define TWIS130_EASYDMALISTINCLUDED 0
#define TWIS130_EASYDMAMODEINCLUDED 0
#define TWIS130_EASYDMAFULLLPMODEINCLUDED 0
#define TWIS130_EASYDMAPATTERNMATCHERINCLUDED 0
#define TWIS130_easyDMAMatchEventRange 4

#define TWIS131_EASYDMA5 0
#define TWIS131_EASYDMATEMP 1
#define TWIS131_EASYDMALISTINCLUDED 0
#define TWIS131_EASYDMAMODEINCLUDED 0
#define TWIS131_EASYDMAFULLLPMODEINCLUDED 0
#define TWIS131_EASYDMAPATTERNMATCHERINCLUDED 0
#define TWIS131_easyDMAMatchEventRange 4

#define TWIS132_EASYDMA5 0
#define TWIS132_EASYDMATEMP 1
#define TWIS132_EASYDMALISTINCLUDED 0
#define TWIS132_EASYDMAMODEINCLUDED 0
#define TWIS132_EASYDMAFULLLPMODEINCLUDED 0
#define TWIS132_EASYDMAPATTERNMATCHERINCLUDED 0
#define TWIS132_easyDMAMatchEventRange 4

#define TWIS133_EASYDMA5 0
#define TWIS133_EASYDMATEMP 1
#define TWIS133_EASYDMALISTINCLUDED 0
#define TWIS133_EASYDMAMODEINCLUDED 0
#define TWIS133_EASYDMAFULLLPMODEINCLUDED 0
#define TWIS133_EASYDMAPATTERNMATCHERINCLUDED 0
#define TWIS133_easyDMAMatchEventRange 4

#define TWIS134_EASYDMA5 0
#define TWIS134_EASYDMATEMP 1
#define TWIS134_EASYDMALISTINCLUDED 0
#define TWIS134_EASYDMAMODEINCLUDED 0
#define TWIS134_EASYDMAFULLLPMODEINCLUDED 0
#define TWIS134_EASYDMAPATTERNMATCHERINCLUDED 0
#define TWIS134_easyDMAMatchEventRange 4

#define TWIS135_EASYDMA5 0
#define TWIS135_EASYDMATEMP 1
#define TWIS135_EASYDMALISTINCLUDED 0
#define TWIS135_EASYDMAMODEINCLUDED 0
#define TWIS135_EASYDMAFULLLPMODEINCLUDED 0
#define TWIS135_EASYDMAPATTERNMATCHERINCLUDED 0
#define TWIS135_easyDMAMatchEventRange 4

#define TWIS136_EASYDMA5 0
#define TWIS136_EASYDMATEMP 1
#define TWIS136_EASYDMALISTINCLUDED 0
#define TWIS136_EASYDMAMODEINCLUDED 0
#define TWIS136_EASYDMAFULLLPMODEINCLUDED 0
#define TWIS136_EASYDMAPATTERNMATCHERINCLUDED 0
#define TWIS136_easyDMAMatchEventRange 4

#define TWIS137_EASYDMA5 0
#define TWIS137_EASYDMATEMP 1
#define TWIS137_EASYDMALISTINCLUDED 0
#define TWIS137_EASYDMAMODEINCLUDED 0
#define TWIS137_EASYDMAFULLLPMODEINCLUDED 0
#define TWIS137_EASYDMAPATTERNMATCHERINCLUDED 0
#define TWIS137_easyDMAMatchEventRange 4


#ifdef __cplusplus
}
#endif
#endif /* NRF9230_PPR_PERIPHERALS_H */

