/*$$$LICENCE_NORDIC_STANDARD<2017>$$$*/

#ifndef NRFX_ERRORS_H__
#define NRFX_ERRORS_H__

#if !defined(NRFX_ERRORS_DEFINED_EXTERNALLY)

/**
@defgroup nrfx_error nrfx Global Error Codes
@{

@brief Global Error definitions
*/

#define NRFX_ERROR_BASE_NUM                 0xBAD00000
#define NRFX_ERROR_SDK_COMMON_ERROR_BASE    (NRFX_ERROR_BASE_NUM +  0x0080)
#define NRFX_ERROR_PERIPH_DRIVERS_ERR_BASE  (NRFX_ERROR_BASE_NUM + 0x10000)

typedef enum {
    NRFX_SUCCESS                = (NRFX_ERROR_BASE_NUM + 0),
    NRFX_ERROR_INTERNAL         = (NRFX_ERROR_BASE_NUM + 3),
    NRFX_ERROR_NO_MEM           = (NRFX_ERROR_BASE_NUM + 4),
    NRFX_ERROR_NOT_SUPPORTED    = (NRFX_ERROR_BASE_NUM + 6),
    NRFX_ERROR_INVALID_PARAM    = (NRFX_ERROR_BASE_NUM + 7),
    NRFX_ERROR_INVALID_STATE    = (NRFX_ERROR_BASE_NUM + 8),
    NRFX_ERROR_INVALID_LENGTH   = (NRFX_ERROR_BASE_NUM + 9),
    NRFX_ERROR_TIMEOUT          = (NRFX_ERROR_BASE_NUM + 13),
    NRFX_ERROR_FORBIDDEN        = (NRFX_ERROR_BASE_NUM + 15),
    NRFX_ERROR_NULL             = (NRFX_ERROR_BASE_NUM + 14),
    NRFX_ERROR_INVALID_ADDR     = (NRFX_ERROR_BASE_NUM + 16),
    NRFX_ERROR_BUSY             = (NRFX_ERROR_BASE_NUM + 17),

    NRFX_ERROR_MODULE_ALREADY_INITIALIZED = (NRFX_ERROR_SDK_COMMON_ERROR_BASE + 0x0005),

    NRFX_ERROR_DRV_TWI_ERR_OVERRUN  = (NRFX_ERROR_PERIPH_DRIVERS_ERR_BASE + 0x0000),
    NRFX_ERROR_DRV_TWI_ERR_ANACK    = (NRFX_ERROR_PERIPH_DRIVERS_ERR_BASE + 0x0001),
    NRFX_ERROR_DRV_TWI_ERR_DNACK    = (NRFX_ERROR_PERIPH_DRIVERS_ERR_BASE + 0x0002)
} ret_code_t;

/**
@}
*/

#endif // NRFX_ERRORS_DEFINED_EXTERNALLY

#endif // NRFX_ERRORS_H__
